// automaticly generated by wsjcpp:v0.5.3

#include "__data_sample_html_index_html_pathdb6d12.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_index_html_pathdb6d12)

const std::string &RES___data_sample_html_index_html_pathdb6d12::getFilename() const {
    static const std::string s = "./data_sample/html/index.html";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_index_html_pathdb6d12::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_index_html_pathdb6d12::getBufferSize() const {
    return 5254;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_index_html_pathdb6d12::getBuffer() const {
    static const std::string sRet = "" // size: 5254
        "<html>\n"
        "<head>\n"
        "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n"
        "    <title>ctf01d</title>\n"
        "    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/favicon-32x32.png\">\n"
        "    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/favicon-16x16.png\">\n"
        "    <link rel=\"stylesheet\" href=\"css/scoreboard.css\">\n"
        "</head>\n"
        "<body>\n"
        "\n"
        "    <div class=\"ctf01d-tabs\">\n"
        "        <div class=\"ctf01d-tab\" tabcontentid=\"game_details\">Details</div>\n"
        "        <div class=\"ctf01d-tab active\" tabcontentid=\"game_scoreboard\">Scoreboard</div>\n"
        "        <!-- div class=\"ctf01d-tab\" tabcontentid=\"game_activities\">Activities</div -->\n"
        "        <div class=\"ctf01d-tab\" tabcontentid=\"game_rules\">Rules</div>\n"
        "    </div>\n"
        "    <div class=\"ctf01d-tab-content\" id=\"game_details\">\n"
        "        <div class=\"game-name\" id=\"game_name\"></div>\n"
        "        <div class=\"game-time-range\" id=\"game_time_range\"></div>\n"
        "        <hr>\n"
        "        <h3>Scoreboard Legend</h3>\n"
        "\n"
        "        <p><div class=\"legend service-status down\"></div> - service is down (dead)</p>\n"
        "        <p><div class=\"legend service-status up\"></div> - service is work (up)</p>\n"
        "        <p><div class=\"legend service-status mumble\"></div> - service is mumble (so slow)</p>\n"
        "        <p><div class=\"legend service-status corrupt\"></div> - service is corrupt</p>\n"
        "        <p><div class=\"legend service-status shit\"></div> - checker is shit (developer of checker for service must fix this)</p>\n"
        "        <p><div class=\"legend activity\"><div class=\"activity-icon\"></div></div> - activities (how much try send flags by team)</p>\n"
        "\n"
        "        <hr>\n"
        "        <h3>Flag send</h3>\n"
        "        <p>The flag format must match the regular expression (uuid):</p>\n"
        "        <pre>\"^c01d[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}[0-9]{8}$\"</pre>\n"
        "        <div style=\"display: inline-block;\">\n"
        "            <pre class=\"pre-flag-format\">\n"
        "Flag example: c01d1fd2-133a-4713-9587-1f6a00000001\n"
        "              c01d...random-data-flag.....time\n"
        "              ^ prefix                    ^ timestamp is the last 8 digits\n"
        "              always c01d                   (how many seconds have passed\n"
        "                                            since the start of the game)\n"
        "            </pre>\n"
        "        </div>\n"
        "\n"
        "\n"
        "        <p>Form for send flag:</p>\n"
        "        <form target=\"_blank\" method=\"GET\" action=\"/flag\">\n"
        "            By Team<select name=\"teamid\" id=\"team_list\"></select>\n"
        "            <input type=\"text\" size=\"36\" placeholder=\"Flag value\" name=\"flag\"> \n"
        "            <button>Send</button><br>\n"
        "        </form>\n"
        "\n"
        "    </div>\n"
        "    <div class=\"ctf01d-tab-content\" id=\"game_rules\">\n"
        "        <h3>1. Basic</h3>\n"
        "        <p>Every flag have a lifetime (default: 1 minute)</p> <!-- TODO get from server -->\n"
        "        <p>Basic cost of stolen flag (default: 10 points)</p> <!-- TODO get from server -->\n"
        "\n"
        "        <h3>2. Acception of flag defence</h3>\n"
        "        <p>Only that flag defence from the service is counted if:</p>\n"
        "        <div>\n"
        "            <p>- the flag was successfully putted to the service</<p>>\n"
        "            <p>- the flag has existed on the service all the time of it's life</<p>>\n"
        "            <p>- the flag was not stolen by another team (s)</<p>>\n"
        "            <p>- the cost of the defences flag is fixed and equal to 1.0 points</<p>> <!-- TODO get from server -->\n"
        "        </div>\n"
        "\n"
        "        <h3>3. Acception of flag attack</h3>\n"
        "\n"
        "        <p>The attack flag counts if:</p>\n"
        "        <div>\n"
        "            <p>- the flag has the correct format</p>\n"
        "            <p>- the flag does not belong to your team (not from your service)</p>\n"
        "            <p>- a flag from the same type of service as yours, but your service must be in UP state</p>\n"
        "            <p>- the flag is dealt the first time by your team (the same flag may be dealt by different teams)</p>\n"
        "            <p>- the flag is still alive (the flag has not expired)</p>\n"
        "            <p>- only during the announced game (flags are not accepted during coffeebreaking)</p>\n"
        "        </div>\n"
        "        <div style=\"display: inline-block;\">\n"
        "            <pre class=\"pre-flag-format\">\n"
        "# formala1\n"
        "basic_flag_points = 1.0\n"
        "motivation = 1.0\n"
        "if victim_place_in_scoreboard > thief_place_in_scoreboard:\n"
        "    motivation -= (victim_place_in_scoreboard - thief_place_in_scoreboard) / (m_nTeamCount - 1);\n"
        "attack_points_by_servece1 = basic_flag_points * motivation\n"
        "\n"
        "# formala2\n"
        "team_points = team_points + SLA_1 * (service1_defence_points + service1_attack_points)\n"
        "team_points = team_points + SLA_2 * (service2_defence_points + service2_attack_points)\n"
        "...\n"
        "team_points = team_points + SLA_N * (serviceN_defence_points + serviceN_attack_points)\n"
        "            </pre>\n"
        "        </div>\n"
        "        <div class=\"game-rule-header\">4. Issues for a jury system</div>\n"
        "        <div class=\"game-rule\">\n"
        "            <a target=\"_blank\" href=\"https://github.com/sea-kg/ctf01d/issues\">https://github.com/sea-kg/ctf01d/issues</a>\n"
        "        </div>\n"
        "    </div>\n"
        "    <div class=\"ctf01d-tab-content\" id=\"game_scoreboard\" style=\"display: block\">\n"
        "        <div id=\"scoreboard_content\" style=\"display: none\">\n"
        "        </div>\n"
        "        <div id=\"loader_content\" style=\"display: block\">\n"
        "            <div class=\"lds-facebook\">\n"
        "                <div></div>\n"
        "                <div></div>\n"
        "                <div></div>\n"
        "            </div>\n"
        "        </div>\n"
        "    </div>\n"
        "<script src=\"js/scoreboard.js\" defer=\"defer\"></script>\n"
        "</body>\n"
        "</html>\n"
        "\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


