// automaticly generated by wsjcpp:v0.4.3

#include <wsjcpp_resources_manager.h>

class RES___data_sample_html_images_states_corrupt_svg_pathc5dd78 : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename() const override;
        virtual const std::string &getPackAs() const override;
        virtual int getBufferSize() const override;
        virtual const char *getBuffer() const override;
};


