// automaticly generated by wsjcpp:v0.5.2

#include "__data_sample_html_images_states_up_svg_path57e5bd.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_images_states_up_svg_path57e5bd)

const std::string &RES___data_sample_html_images_states_up_svg_path57e5bd::getFilename() const {
    static const std::string s = "./data_sample/html/images/states/up.svg";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_images_states_up_svg_path57e5bd::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_images_states_up_svg_path57e5bd::getBufferSize() const {
    return 4172;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_images_states_up_svg_path57e5bd::getBuffer() const {
    static const std::string sRet = "" // size: 4172
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->\n"
        "\n"
        "<svg\n"
        "   version=\"1.1\"\n"
        "   id=\"Layer_1\"\n"
        "   x=\"0px\"\n"
        "   y=\"0px\"\n"
        "   width=\"512px\"\n"
        "   height=\"512px\"\n"
        "   viewBox=\"0 0 512 512\"\n"
        "   enable-background=\"new 0 0 512 512\"\n"
        "   xml:space=\"preserve\"\n"
        "   sodipodi:docname=\"up.svg\"\n"
        "   inkscape:version=\"1.1.2 (0a00cf5339, 2022-02-04)\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"><metadata\n"
        "   id=\"metadata13\"><rdf:RDF><cc:Work\n"
        "       rdf:about=\"\"><dc:format>image/svg+xml</dc:format><dc:type\n"
        "         rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" /></cc:Work></rdf:RDF></metadata><defs\n"
        "   id=\"defs11\"><filter\n"
        "     inkscape:collect=\"always\"\n"
        "     style=\"color-interpolation-filters:sRGB\"\n"
        "     id=\"filter863\"\n"
        "     x=\"-0.077971964\"\n"
        "     y=\"-0.075459472\"\n"
        "     width=\"1.1559439\"\n"
        "     height=\"1.1509189\"><feGaussianBlur\n"
        "       inkscape:collect=\"always\"\n"
        "       stdDeviation=\"15.123336\"\n"
        "       id=\"feGaussianBlur865\" /></filter></defs><sodipodi:namedview\n"
        "   pagecolor=\"#000000\"\n"
        "   bordercolor=\"#666666\"\n"
        "   borderopacity=\"1\"\n"
        "   objecttolerance=\"10\"\n"
        "   gridtolerance=\"10\"\n"
        "   guidetolerance=\"10\"\n"
        "   inkscape:pageopacity=\"0\"\n"
        "   inkscape:pageshadow=\"2\"\n"
        "   inkscape:window-width=\"2490\"\n"
        "   inkscape:window-height=\"1376\"\n"
        "   id=\"namedview9\"\n"
        "   showgrid=\"false\"\n"
        "   inkscape:zoom=\"0.4609375\"\n"
        "   inkscape:cx=\"256\"\n"
        "   inkscape:cy=\"159.45763\"\n"
        "   inkscape:window-x=\"70\"\n"
        "   inkscape:window-y=\"27\"\n"
        "   inkscape:window-maximized=\"1\"\n"
        "   inkscape:current-layer=\"Layer_1\"\n"
        "   inkscape:pagecheckerboard=\"0\" />\n"
        "<g\n"
        "   id=\"g6\"\n"
        "   style=\"opacity:1;fill:#00ce00;fill-opacity:1\"\n"
        "   transform=\"matrix(0.6830823,0,0,0.6830823,83.964673,83.281904)\">\n"
        "	<path\n"
        "   d=\"m 483.932,47.29 c -26.72,21.71 -55.73,42.46 -89.55,51.16 -20.05,5.17 -41.561,4.15 -61.05,-2.83 -32.49,-11.5 -59.341,-34.58 -91.771,-46.22 -19.03,-7.16 -39.91,-9.12 -59.95,-5.83 -29.68,4.86 -56.739,19.26 -81.62,35.58 -0.1,86.75 -0.039,173.51 -0.029,260.27 25.46,-16.641 53.189,-31.38 83.63,-35.891 21.93,-3.389 44.66,0.061 64.97,8.871 27.48,11.369 51.18,30.14 78.811,41.209 19.33,7.971 41,10.641 61.529,6.311 36.04,-7.58 66.9,-29.439 94.97,-52.29 0.22,-86.771 0.1,-173.56 0.06,-260.34 z\"\n"
        "   id=\"path2\"\n"
        "   style=\"fill:#00ce00;fill-opacity:1\"\n"
        "   inkscape:connector-curvature=\"0\" />\n"
        "	<path\n"
        "   d=\"M 73.5,426.784 V 73.216 c 9.064,-6.325 15,-16.824 15,-28.716 0,-19.33 -15.67,-35 -35,-35 -19.33,0 -35,15.67 -35,35 0,11.892 5.936,22.391 15,28.716 v 353.568 c -9.064,6.325 -15,16.824 -15,28.716 0,19.33 15.67,35 35,35 19.33,0 35,-15.67 35,-35 0,-11.892 -5.935,-22.391 -15,-28.716 z\"\n"
        "   id=\"path4\"\n"
        "   style=\"fill:#00ce00;fill-opacity:1\"\n"
        "   inkscape:connector-curvature=\"0\" />\n"
        "</g><g\n"
        "   id=\"g6-3\"\n"
        "   style=\"fill:#b1f28c;fill-opacity:1;filter:url(#filter863);opacity:0.58102451\"\n"
        "   transform=\"matrix(0.6830823,0,0,0.6830823,83.964673,83.281904)\"><path\n"
        "     d=\"m 483.932,47.29 c -26.72,21.71 -55.73,42.46 -89.55,51.16 -20.05,5.17 -41.561,4.15 -61.05,-2.83 -32.49,-11.5 -59.341,-34.58 -91.771,-46.22 -19.03,-7.16 -39.91,-9.12 -59.95,-5.83 -29.68,4.86 -56.739,19.26 -81.62,35.58 -0.1,86.75 -0.039,173.51 -0.029,260.27 25.46,-16.641 53.189,-31.38 83.63,-35.891 21.93,-3.389 44.66,0.061 64.97,8.871 27.48,11.369 51.18,30.14 78.811,41.209 19.33,7.971 41,10.641 61.529,6.311 36.04,-7.58 66.9,-29.439 94.97,-52.29 0.22,-86.771 0.1,-173.56 0.06,-260.34 z\"\n"
        "     id=\"path2-6\"\n"
        "     style=\"fill:#b1f28c;fill-opacity:1\"\n"
        "     inkscape:connector-curvature=\"0\" /><path\n"
        "     d=\"M 73.5,426.784 V 73.216 c 9.064,-6.325 15,-16.824 15,-28.716 0,-19.33 -15.67,-35 -35,-35 -19.33,0 -35,15.67 -35,35 0,11.892 5.936,22.391 15,28.716 v 353.568 c -9.064,6.325 -15,16.824 -15,28.716 0,19.33 15.67,35 35,35 19.33,0 35,-15.67 35,-35 0,-11.892 -5.935,-22.391 -15,-28.716 z\"\n"
        "     id=\"path4-7\"\n"
        "     style=\"fill:#b1f28c;fill-opacity:1\"\n"
        "     inkscape:connector-curvature=\"0\" /></g>\n"
        "</svg>\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


