// automaticly generated by wsjcpp:v0.5.2

#include "__data_sample_html_images_states_mumble_svg_pathade7e3.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_images_states_mumble_svg_pathade7e3)

const std::string &RES___data_sample_html_images_states_mumble_svg_pathade7e3::getFilename() const {
    static const std::string s = "./data_sample/html/images/states/mumble.svg";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_images_states_mumble_svg_pathade7e3::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_images_states_mumble_svg_pathade7e3::getBufferSize() const {
    return 3513;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_images_states_mumble_svg_pathade7e3::getBuffer() const {
    static const std::string sRet = "" // size: 3513
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) by Toomai Glittershine for SmashWiki -->\n"
        "\n"
        "<svg\n"
        "   id=\"svg2\"\n"
        "   version=\"1.1\"\n"
        "   height=\"256\"\n"
        "   width=\"256\"\n"
        "   viewBox=\"0 0 256 256\"\n"
        "   sodipodi:docname=\"mumble.svg\"\n"
        "   inkscape:version=\"1.1.2 (0a00cf5339, 2022-02-04)\"\n"
        "   inkscape:export-filename=\"mumble.png\"\n"
        "   inkscape:export-xdpi=\"75\"\n"
        "   inkscape:export-ydpi=\"75\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n"
        "  <defs\n"
        "     id=\"defs8\" />\n"
        "  <sodipodi:namedview\n"
        "     pagecolor=\"#000000\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1\"\n"
        "     objecttolerance=\"10\"\n"
        "     gridtolerance=\"10\"\n"
        "     guidetolerance=\"10\"\n"
        "     inkscape:pageopacity=\"0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:window-width=\"2490\"\n"
        "     inkscape:window-height=\"1376\"\n"
        "     id=\"namedview6\"\n"
        "     showgrid=\"false\"\n"
        "     inkscape:zoom=\"1.84375\"\n"
        "     inkscape:cx=\"210.98305\"\n"
        "     inkscape:cy=\"61.016949\"\n"
        "     inkscape:window-x=\"70\"\n"
        "     inkscape:window-y=\"27\"\n"
        "     inkscape:window-maximized=\"1\"\n"
        "     inkscape:current-layer=\"svg2\"\n"
        "     inkscape:pagecheckerboard=\"0\" />\n"
        "  <metadata\n"
        "     id=\"metadata7\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <path\n"
        "     id=\"path886\"\n"
        "     style=\"fill:#d3868c;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.854395px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "     d=\"m 192.26347,10.811507 -5.3789,77.416016 -15.15235,37.734367 C 168.43584,107.83777 165.27069,84.554711 148.26738,75.37596 132.29049,68.287201 112.71413,66.095513 93.872849,67.72557 75.681308,70.185464 63.004789,80.422844 51.863083,92.821273 35.993926,111.87044 30.538605,134.61942 38.118942,153.69041 l 35.140625,44.1582 -48.669922,15.22071 0.923828,10.04687 34.171876,-3.19336 23.808593,4.35938 19.662108,-5.78321 22.62109,4.87891 27.89454,-5.3418 15.80468,3.94141 c 20.70907,-3.18659 24.92042,-8.96927 27.18946,-20.94141 l -2.70703,-34.68554 19.86914,-43.48047 c 3.15765,-1.24618 4.62117,-0.9835 7.65739,-4.81949 0.86257,-4.13567 1.43008,-5.91601 -1.78739,-6.73763 l 11.43727,-13.540086 -10.93813,-26.600059 0.90039,-40.992187 -14.53125,39.705078 -8.1543,1.666016 z m 10.48514,82.586147 6.62919,-4.825532 7.08945,6.070552 -5.69856,-1.686493 -4.70961,-0.134466 z m -110.564652,28.744756 -0.637309,9.4079 -10.993571,18.41296 8.885837,1.08983 4.907873,0.69975 14.816592,-12.1762 -12.43288,-0.94012 1.453111,-7.06116 24.659839,0.69349 -1.37988,5.19286 -17.91788,14.42201 22.42746,-0.007 21.27426,-13.37718 -15.93022,-0.18714 0.37771,-6.23999 24.40328,1.47826 -0.12315,5.78904 -20.22905,14.04932 19.25948,0.33167 c 9.23002,-5.93388 13.47896,-20.51454 27.69005,-17.80164 8.47586,5.92385 6.73153,11.32075 -3.14511,14.51426 l -24.08206,4.9649 -0.28673,5.21569 -26.51309,-1.74097 -4.37194,-4.81815 -4.02322,4.26688 -25.621579,-1.68243 -3.073475,-3.7439 -1.563551,3.37912 -20.699067,-1.25419 15.33611,-23.34112 -13.782907,-1.74218 0.95075,-8.05117 z\"\n"
        "     sodipodi:nodetypes=\"ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc\" />\n"
        "</svg>\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


