// automaticly generated by wsjcpp:v0.5.1

#include "__data_sample_html_images_defence_points_svg_path5ccfa0.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_images_defence_points_svg_path5ccfa0)

const std::string &RES___data_sample_html_images_defence_points_svg_path5ccfa0::getFilename() const {
    static const std::string s = "./data_sample/html/images/defence-points.svg";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_images_defence_points_svg_path5ccfa0::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_images_defence_points_svg_path5ccfa0::getBufferSize() const {
    return 4364;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_images_defence_points_svg_path5ccfa0::getBuffer() const {
    static const std::string sRet = "" // size: 4364
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) -->\n"
        "\n"
        "<svg\n"
        "   width=\"100\"\n"
        "   height=\"100\"\n"
        "   viewBox=\"0 0 26.458333 26.458334\"\n"
        "   version=\"1.1\"\n"
        "   id=\"svg8\"\n"
        "   inkscape:version=\"1.1.2 (0a00cf5339, 2022-02-04)\"\n"
        "   sodipodi:docname=\"defence-points.svg\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n"
        "  <defs\n"
        "     id=\"defs2\" />\n"
        "  <sodipodi:namedview\n"
        "     id=\"base\"\n"
        "     pagecolor=\"#ffffff\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1.0\"\n"
        "     inkscape:pageopacity=\"0.0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:zoom=\"5.6\"\n"
        "     inkscape:cx=\"68.214286\"\n"
        "     inkscape:cy=\"61.339286\"\n"
        "     inkscape:document-units=\"px\"\n"
        "     inkscape:current-layer=\"layer1\"\n"
        "     showgrid=\"false\"\n"
        "     units=\"mm\"\n"
        "     inkscape:window-width=\"2490\"\n"
        "     inkscape:window-height=\"1376\"\n"
        "     inkscape:window-x=\"70\"\n"
        "     inkscape:window-y=\"27\"\n"
        "     inkscape:window-maximized=\"1\"\n"
        "     inkscape:snap-global=\"false\"\n"
        "     inkscape:pagecheckerboard=\"0\" />\n"
        "  <metadata\n"
        "     id=\"metadata5\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <g\n"
        "     inkscape:label=\"Layer 1\"\n"
        "     inkscape:groupmode=\"layer\"\n"
        "     id=\"layer1\"\n"
        "     transform=\"translate(0,-270.54166)\">\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-3\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-1\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <path\n"
        "       style=\"fill:#00b100;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.399258px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "       d=\"m 8.0663766,270.77416 0.07564,6.95739 -0.503752,-0.0756 v 2.29418 l -1.613407,-0.0257 v -2.24349 l -1.9159703,-0.025 0.025733,2.29419 -1.6391412,-0.10142 -0.024954,-2.09222 -1.84032962,-0.025 -0.1005947,6.30157 2.21853272,0.0507 -2.26921982,12.55323 16.08261032,0.0499 -2.117939,-12.60313 1.91597,-0.0257 0.151282,-6.30158 -1.714003,-0.025 -0.02495,2.16785 -1.815377,-0.0756 0.07563,-2.0922 -1.814597,-0.0507 -0.02573,2.29417 H 9.4778066 l -0.04991,-2.31913 -0.403157,-0.025 -0.08613,-2.7683 c 2.3088874,1.73553 4.7232964,-1.47062 7.6500894,0.62095 l 0.0025,-4.02348 c -2.517407,-1.04274 -6.075493,1.16429 -7.5415374,-0.68596 z m 0.554438,15.45176 2.0672524,1.66408 -0.07564,4.08305 -4.1087704,-0.025 -0.05069,-4.13372 z\"\n"
        "       id=\"path857\"\n"
        "       inkscape:connector-curvature=\"0\"\n"
        "       sodipodi:nodetypes=\"cccccccccccccccccccccccccccccccccccccc\" />\n"
        "    <g\n"
        "       id=\"g831\"\n"
        "       transform=\"matrix(0.6563753,0,0,0.62729614,8.1003751,106.08702)\">\n"
        "      <path\n"
        "         style=\"fill:#ffe600;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.334308px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "         d=\"m 4.522599,289.63405 2.3282191,-7.04435 -6.02949182,-4.17886 7.16375252,-0.1791 2.4476152,-6.86525 2.208825,7.04435 7.342847,0.0598 -5.850398,4.17886 2.387919,7.22345 -6.029495,-4.47734 z\"\n"
        "         id=\"path826-3\"\n"
        "         inkscape:connector-curvature=\"0\" />\n"
        "      <path\n"
        "         style=\"fill:#ff6700;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.264583px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "         d=\"m 13.708745,289.40582 1.842634,-5.57514 -4.77195,-3.3073 5.669643,-0.14174 1.937128,-5.4334 1.74814,5.57514 5.811384,0.0473 -4.630208,3.30729 1.889881,5.71689 -4.77195,-3.54352 z\"\n"
        "         id=\"path826\"\n"
        "         inkscape:connector-curvature=\"0\" />\n"
        "      <path\n"
        "         style=\"fill:#4be600;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.264583px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "         d=\"m 7.3942979,296.36898 1.8426337,-5.57514 -4.7719497,-3.3073 5.6696431,-0.14174 1.937128,-5.4334 1.74814,5.57514 5.811384,0.0473 -4.630208,3.30729 1.889881,5.71689 -4.77195,-3.54352 z\"\n"
        "         id=\"path826-6\"\n"
        "         inkscape:connector-curvature=\"0\" />\n"
        "    </g>\n"
        "  </g>\n"
        "</svg>\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


