// automaticly generated by wsjcpp:v0.5.2

#include "__data_sample_html_images_attack_svg_pathccf68d.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_images_attack_svg_pathccf68d)

const std::string &RES___data_sample_html_images_attack_svg_pathccf68d::getFilename() const {
    static const std::string s = "./data_sample/html/images/attack.svg";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_images_attack_svg_pathccf68d::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_images_attack_svg_pathccf68d::getBufferSize() const {
    return 2887;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_images_attack_svg_pathccf68d::getBuffer() const {
    static const std::string sRet = "" // size: 2887
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) -->\n"
        "\n"
        "<svg\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   width=\"100\"\n"
        "   height=\"100\"\n"
        "   viewBox=\"0 0 26.458333 26.458334\"\n"
        "   version=\"1.1\"\n"
        "   id=\"svg8\"\n"
        "   inkscape:version=\"0.92.3 (2405546, 2018-03-11)\"\n"
        "   sodipodi:docname=\"attack.svg\">\n"
        "  <defs\n"
        "     id=\"defs2\" />\n"
        "  <sodipodi:namedview\n"
        "     id=\"base\"\n"
        "     pagecolor=\"#ffffff\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1.0\"\n"
        "     inkscape:pageopacity=\"0.0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:zoom=\"3.959798\"\n"
        "     inkscape:cx=\"23.624672\"\n"
        "     inkscape:cy=\"49.557662\"\n"
        "     inkscape:document-units=\"px\"\n"
        "     inkscape:current-layer=\"layer1\"\n"
        "     showgrid=\"false\"\n"
        "     units=\"px\"\n"
        "     inkscape:window-width=\"1853\"\n"
        "     inkscape:window-height=\"1025\"\n"
        "     inkscape:window-x=\"67\"\n"
        "     inkscape:window-y=\"27\"\n"
        "     inkscape:window-maximized=\"1\"\n"
        "     inkscape:snap-global=\"false\" />\n"
        "  <metadata\n"
        "     id=\"metadata5\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "        <dc:title />\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <g\n"
        "     inkscape:label=\"Layer 1\"\n"
        "     inkscape:groupmode=\"layer\"\n"
        "     id=\"layer1\"\n"
        "     transform=\"translate(0,-270.54166)\">\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-3\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-1\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <path\n"
        "       style=\"fill:#cc5914;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.30876076px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "       d=\"m 4.4822084,293.53427 c 0.2339217,0.039 1.4035298,-0.15594 1.4035298,-0.15594 l 0.1169607,1.28657 1.9883335,2.14428 1.7154251,-1.32555 -0.3898687,-5.0683 1.5594772,-1.83239 5.536144,5.02931 1.988335,-1.52049 -0.155949,-1.71543 2.807059,-3.2749 -2.729085,1.20859 -0.116961,-1.1696 2.378203,-3.002 -2.495164,0.89671 -0.272908,-1.48151 6.198922,-8.46017 2.378204,-4.36653 -4.71742,2.18328 -8.421178,6.39385 -1.598464,-0.19493 1.520491,-2.41719 -3.6257852,2.33921 -1.4425163,-0.23392 1.832386,-2.6901 -3.4308504,2.22224 H 4.9890385 l -1.8323858,1.91038 5.302223,5.26323 -1.9493466,1.98834 -4.6784321,-0.3119 -1.67643828,1.16961 2.41718998,2.72908 1.2286624,-0.0618 -0.5812219,0.99279 z\"\n"
        "       id=\"path892\"\n"
        "       inkscape:connector-curvature=\"0\"\n"
        "       sodipodi:nodetypes=\"cccccccccccccccccccccccccccccccccccc\" />\n"
        "  </g>\n"
        "</svg>\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


