// automaticly generated by wsjcpp:v0.5.0

#include <wsjcpp_core.h>

class RES___data_sample_checker_example_service1_checker_py_path0d8a63 : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename() const override;
        virtual const std::string &getPackAs() const override;
        virtual int getBufferSize() const override;
        virtual const char *getBuffer() const override;
};


