// automaticly generated by wsjcpp:v0.5.1

#include "__data_sample_html_images_states_place_1st_svg_pathe81cb6.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_images_states_place_1st_svg_pathe81cb6)

const std::string &RES___data_sample_html_images_states_place_1st_svg_pathe81cb6::getFilename() const {
    static const std::string s = "./data_sample/html/images/states/place-1st.svg";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_images_states_place_1st_svg_pathe81cb6::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_images_states_place_1st_svg_pathe81cb6::getBufferSize() const {
    return 4727;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_images_states_place_1st_svg_pathe81cb6::getBuffer() const {
    static const std::string sRet = "" // size: 4727
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->\n"
        "\n"
        "<svg\n"
        "   version=\"1.1\"\n"
        "   id=\"Layer_1\"\n"
        "   x=\"0px\"\n"
        "   y=\"0px\"\n"
        "   width=\"512px\"\n"
        "   height=\"512px\"\n"
        "   viewBox=\"0 0 512 512\"\n"
        "   enable-background=\"new 0 0 512 512\"\n"
        "   xml:space=\"preserve\"\n"
        "   sodipodi:docname=\"place-1st.svg\"\n"
        "   inkscape:version=\"1.1.2 (0a00cf5339, 2022-02-04)\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"><metadata\n"
        "   id=\"metadata13\"><rdf:RDF><cc:Work\n"
        "       rdf:about=\"\"><dc:format>image/svg+xml</dc:format><dc:type\n"
        "         rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" /></cc:Work></rdf:RDF></metadata><defs\n"
        "   id=\"defs11\"><filter\n"
        "     inkscape:collect=\"always\"\n"
        "     style=\"color-interpolation-filters:sRGB\"\n"
        "     id=\"filter11419\"\n"
        "     x=\"-0.08417406\"\n"
        "     y=\"-0.090899719\"\n"
        "     width=\"1.1683481\"\n"
        "     height=\"1.1817994\"><feGaussianBlur\n"
        "       inkscape:collect=\"always\"\n"
        "       stdDeviation=\"11.681654\"\n"
        "       id=\"feGaussianBlur11421\" /></filter></defs><sodipodi:namedview\n"
        "   pagecolor=\"#000000\"\n"
        "   bordercolor=\"#666666\"\n"
        "   borderopacity=\"1\"\n"
        "   objecttolerance=\"10\"\n"
        "   gridtolerance=\"10\"\n"
        "   guidetolerance=\"10\"\n"
        "   inkscape:pageopacity=\"0\"\n"
        "   inkscape:pageshadow=\"2\"\n"
        "   inkscape:window-width=\"2490\"\n"
        "   inkscape:window-height=\"1376\"\n"
        "   id=\"namedview9\"\n"
        "   showgrid=\"false\"\n"
        "   inkscape:zoom=\"0.4609375\"\n"
        "   inkscape:cx=\"-778.84746\"\n"
        "   inkscape:cy=\"352.54237\"\n"
        "   inkscape:window-x=\"70\"\n"
        "   inkscape:window-y=\"27\"\n"
        "   inkscape:window-maximized=\"1\"\n"
        "   inkscape:current-layer=\"Layer_1\"\n"
        "   inkscape:pagecheckerboard=\"0\" />\n"
        "\n"
        "<path\n"
        "   id=\"path3760\"\n"
        "   style=\"fill:#c4f546;fill-opacity:0.630851;fill-rule:evenodd;stroke:none;stroke-width:1.16773px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "   d=\"m 380.1202,308.57022 c -30.35196,29.40783 -70.90169,49.92504 -121.57533,51.81369 l 45.40404,101.51963 45.28188,-60.60351 77.03566,16.5032 z m -121.57533,51.81369 c -44.90168,-0.19053 -84.60945,-14.7382 -119.07209,-43.78889 l -48.564202,101.10214 79.753262,-14.63466 43.72599,57.63371 z\"\n"
        "   sodipodi:nodetypes=\"cccccccccccc\" /><path\n"
        "   style=\"fill:#b1ce00;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:1.20602px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "   d=\"M 267.3727,75.756566 C 170.92284,77.012288 120.21574,133.41785 119.37312,196.605 120.09079,265.58504 175.17494,324.14392 267.3727,324.76876 352.49429,323.39939 399.68458,265.345 400.90158,196.605 398.29111,127.1465 346.06854,77.704783 267.3727,75.756566 Z\"\n"
        "   id=\"path7712\"\n"
        "   sodipodi:nodetypes=\"ccccc\" /><path\n"
        "   id=\"path902-3\"\n"
        "   style=\"fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:1.16773px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1;filter:url(#filter11419)\"\n"
        "   d=\"M 260.50182,51.92995 C 168.42794,52.77181 86.886321,116.38492 88.366151,198.764 89.856251,284.75446 148.33665,361.81385 260.50182,360.33651 356.2062,359.21362 421.70801,285.19154 421.41672,198.764 421.24511,115.06445 348.58512,52.60351 260.50182,51.92995 Z m 0,28.02137 c 81.52741,5.03437 129.17336,54.00754 128.79923,118.81268 -4.80138,84.60589 -54.72346,120.71284 -128.79923,123.48177 -77.45657,-5.78292 -138.63109,-52.52288 -141.1287,-123.48177 1.3808,-59.58475 59.14573,-117.76573 141.1287,-118.81268 z\"\n"
        "   sodipodi:nodetypes=\"cccccccccc\" /><path\n"
        "   id=\"path902\"\n"
        "   style=\"fill:#b1ff00;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:1.16773px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "   d=\"M 260.50182,51.929953 C 168.42794,52.77181 86.886318,116.38492 88.366148,198.764 89.856248,284.75446 148.33665,361.81385 260.50182,360.33651 356.2062,359.21362 421.70801,285.19154 421.41672,198.764 421.24511,115.06445 348.58512,52.603507 260.50182,51.929953 Z m 0,28.021368 C 342.02923,84.985688 389.67518,133.95886 389.30105,198.764 384.49967,283.36989 334.57759,319.47684 260.50182,322.24577 183.04525,316.46285 121.87073,269.72289 119.37312,198.764 120.75392,139.17925 178.51885,80.998274 260.50182,79.951321 Z\"\n"
        "   sodipodi:nodetypes=\"cccccccccc\" /><path\n"
        "   style=\"fill:#934e00;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:5;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1;stroke-miterlimit:4;stroke-dasharray:none\"\n"
        "   d=\"m 234.0642,277.2089 46.36907,1.43916 0.2419,-147.7487 -34.93771,-0.36199 -34.24533,26.06868 -1.23049,27.11586 31.45186,-19.94336 z\"\n"
        "   id=\"path7413\" /></svg>\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


