// automaticly generated by wsjcpp:v0.5.2

#include "__data_sample_html_images_trend_middle_svg_path61166e.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_images_trend_middle_svg_path61166e)

const std::string &RES___data_sample_html_images_trend_middle_svg_path61166e::getFilename() const {
    static const std::string s = "./data_sample/html/images/trend-middle.svg";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_images_trend_middle_svg_path61166e::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_images_trend_middle_svg_path61166e::getBufferSize() const {
    return 2286;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_images_trend_middle_svg_path61166e::getBuffer() const {
    static const std::string sRet = "" // size: 2286
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) -->\n"
        "\n"
        "<svg\n"
        "   width=\"100\"\n"
        "   height=\"100\"\n"
        "   viewBox=\"0 0 26.458333 26.458334\"\n"
        "   version=\"1.1\"\n"
        "   id=\"svg8\"\n"
        "   inkscape:version=\"1.1.2 (0a00cf5339, 2022-02-04)\"\n"
        "   sodipodi:docname=\"trend-middle.svg\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n"
        "  <defs\n"
        "     id=\"defs2\" />\n"
        "  <sodipodi:namedview\n"
        "     id=\"base\"\n"
        "     pagecolor=\"#ffffff\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1.0\"\n"
        "     inkscape:pageopacity=\"0.0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:zoom=\"5.6\"\n"
        "     inkscape:cx=\"68.392857\"\n"
        "     inkscape:cy=\"38.660714\"\n"
        "     inkscape:document-units=\"px\"\n"
        "     inkscape:current-layer=\"layer1\"\n"
        "     showgrid=\"false\"\n"
        "     units=\"mm\"\n"
        "     inkscape:window-width=\"2490\"\n"
        "     inkscape:window-height=\"1376\"\n"
        "     inkscape:window-x=\"70\"\n"
        "     inkscape:window-y=\"27\"\n"
        "     inkscape:window-maximized=\"1\"\n"
        "     inkscape:snap-global=\"false\"\n"
        "     inkscape:pagecheckerboard=\"0\" />\n"
        "  <metadata\n"
        "     id=\"metadata5\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <g\n"
        "     inkscape:label=\"Layer 1\"\n"
        "     inkscape:groupmode=\"layer\"\n"
        "     id=\"layer1\"\n"
        "     transform=\"translate(0,-270.54166)\">\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-3\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-1\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <path\n"
        "       style=\"fill:#868686;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.250708px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "       d=\"m 1.4466717,286.11259 18.4234183,-0.63713 -0.09573,1.76069 5.48898,-2.53693 -5.590535,-3.36021 0.222923,2.07694 -18.441355,-0.73022 z\"\n"
        "       id=\"path882\"\n"
        "       sodipodi:nodetypes=\"cccccccc\" />\n"
        "  </g>\n"
        "</svg>\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


