// automaticly generated by wsjcpp:v0.5.2

#include "__data_sample_html_images_points_svg_pathbfd704.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_images_points_svg_pathbfd704)

const std::string &RES___data_sample_html_images_points_svg_pathbfd704::getFilename() const {
    static const std::string s = "./data_sample/html/images/points.svg";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_images_points_svg_pathbfd704::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_images_points_svg_pathbfd704::getBufferSize() const {
    return 2979;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_images_points_svg_pathbfd704::getBuffer() const {
    static const std::string sRet = "" // size: 2979
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) -->\n"
        "\n"
        "<svg\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   width=\"100\"\n"
        "   height=\"100\"\n"
        "   viewBox=\"0 0 26.458333 26.458334\"\n"
        "   version=\"1.1\"\n"
        "   id=\"svg8\"\n"
        "   inkscape:version=\"0.92.3 (2405546, 2018-03-11)\"\n"
        "   sodipodi:docname=\"points.svg\">\n"
        "  <defs\n"
        "     id=\"defs2\" />\n"
        "  <sodipodi:namedview\n"
        "     id=\"base\"\n"
        "     pagecolor=\"#ffffff\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1.0\"\n"
        "     inkscape:pageopacity=\"0.0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:zoom=\"5.6\"\n"
        "     inkscape:cx=\"59.537015\"\n"
        "     inkscape:cy=\"50.060612\"\n"
        "     inkscape:document-units=\"mm\"\n"
        "     inkscape:current-layer=\"layer1\"\n"
        "     showgrid=\"false\"\n"
        "     units=\"px\"\n"
        "     inkscape:snap-global=\"false\"\n"
        "     inkscape:window-width=\"1853\"\n"
        "     inkscape:window-height=\"1025\"\n"
        "     inkscape:window-x=\"67\"\n"
        "     inkscape:window-y=\"27\"\n"
        "     inkscape:window-maximized=\"1\" />\n"
        "  <metadata\n"
        "     id=\"metadata5\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "        <dc:title></dc:title>\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <g\n"
        "     inkscape:label=\"Layer 1\"\n"
        "     inkscape:groupmode=\"layer\"\n"
        "     id=\"layer1\"\n"
        "     transform=\"translate(0,-270.54165)\">\n"
        "    <path\n"
        "       style=\"fill:#ffe600;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.33430848px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "       d=\"m 4.522599,289.63405 2.3282191,-7.04435 -6.02949182,-4.17886 7.16375252,-0.1791 2.4476152,-6.86525 2.208825,7.04435 7.342847,0.0598 -5.850398,4.17886 2.387919,7.22345 -6.029495,-4.47734 z\"\n"
        "       id=\"path826-3\"\n"
        "       inkscape:connector-curvature=\"0\" />\n"
        "    <path\n"
        "       style=\"fill:#ff6700;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "       d=\"m 13.708745,289.40582 1.842634,-5.57514 -4.77195,-3.3073 5.669643,-0.14174 1.937128,-5.4334 1.74814,5.57514 5.811384,0.0473 -4.630208,3.30729 1.889881,5.71689 -4.77195,-3.54352 z\"\n"
        "       id=\"path826\"\n"
        "       inkscape:connector-curvature=\"0\" />\n"
        "    <path\n"
        "       style=\"fill:#4be600;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "       d=\"m 7.3942979,296.36898 1.8426337,-5.57514 -4.7719497,-3.3073 5.6696431,-0.14174 1.937128,-5.4334 1.74814,5.57514 5.811384,0.0473 -4.630208,3.30729 1.889881,5.71689 -4.77195,-3.54352 z\"\n"
        "       id=\"path826-6\"\n"
        "       inkscape:connector-curvature=\"0\" />\n"
        "  </g>\n"
        "</svg>\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


