// automaticly generated by wsjcpp:v0.4.3

#include <wsjcpp_resources_manager.h>

class RES___data_sample_logs__placeholder_path8997d4 : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename();
        virtual const std::string &getPackAs();
        virtual const int getBufferSize();
        virtual const char *getBuffer();
};


