// automaticly generated by wsjcpp:v0.5.1

#include <wsjcpp_core.h>

class RES___data_sample_html_images_teams_team05_png_pathad789e : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename() const override;
        virtual const std::string &getPackAs() const override;
        virtual int getBufferSize() const override;
        virtual const char *getBuffer() const override;
};


