// automaticly generated by wsjcpp:v0.5.3

#include "__data_sample_hv_logs__placeholder_path0689c4.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_hv_logs__placeholder_path0689c4)

const std::string &RES___data_sample_hv_logs__placeholder_path0689c4::getFilename() const {
    static const std::string s = "./data_sample/hv_logs/.placeholder";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_hv_logs__placeholder_path0689c4::getPackAs() const {
    static const std::string s = "binary";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_hv_logs__placeholder_path0689c4::getBufferSize() const {
    return 0;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_hv_logs__placeholder_path0689c4::getBuffer() const {
    static const unsigned char b[0] = {
    };
    return (const char*)b;
} //::buffer()


