// automaticly generated by wsjcpp:v0.4.3

#include <wsjcpp_resources_manager.h>

class RES___data_sample_checker_example_service1_checker_py_path0d8a63 : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename();
        virtual const std::string &getPackAs();
        virtual const int getBufferSize();
        virtual const char *getBuffer();
};


