// automaticly generated by wsjcpp:v0.5.2

#include "__data_sample_html_images_first_blood_svg_pathd14a70.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_images_first_blood_svg_pathd14a70)

const std::string &RES___data_sample_html_images_first_blood_svg_pathd14a70::getFilename() const {
    static const std::string s = "./data_sample/html/images/first-blood.svg";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_images_first_blood_svg_pathd14a70::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_images_first_blood_svg_pathd14a70::getBufferSize() const {
    return 3653;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_images_first_blood_svg_pathd14a70::getBuffer() const {
    static const std::string sRet = "" // size: 3653
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) -->\n"
        "\n"
        "<svg\n"
        "   width=\"100\"\n"
        "   height=\"100\"\n"
        "   viewBox=\"0 0 26.458333 26.458334\"\n"
        "   version=\"1.1\"\n"
        "   id=\"svg8\"\n"
        "   inkscape:version=\"1.1.2 (0a00cf5339, 2022-02-04)\"\n"
        "   sodipodi:docname=\"first-blood.svg\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n"
        "  <defs\n"
        "     id=\"defs2\" />\n"
        "  <sodipodi:namedview\n"
        "     id=\"base\"\n"
        "     pagecolor=\"#ffffff\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1.0\"\n"
        "     inkscape:pageopacity=\"0.0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:zoom=\"5.6\"\n"
        "     inkscape:cx=\"89.107143\"\n"
        "     inkscape:cy=\"18.839286\"\n"
        "     inkscape:document-units=\"mm\"\n"
        "     inkscape:current-layer=\"layer1\"\n"
        "     showgrid=\"false\"\n"
        "     units=\"px\"\n"
        "     inkscape:window-width=\"2490\"\n"
        "     inkscape:window-height=\"1376\"\n"
        "     inkscape:window-x=\"70\"\n"
        "     inkscape:window-y=\"27\"\n"
        "     inkscape:window-maximized=\"1\"\n"
        "     inkscape:pagecheckerboard=\"0\" />\n"
        "  <metadata\n"
        "     id=\"metadata5\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <g\n"
        "     inkscape:label=\"Layer 1\"\n"
        "     inkscape:groupmode=\"layer\"\n"
        "     id=\"layer1\"\n"
        "     transform=\"translate(0,-270.54165)\">\n"
        "    <path\n"
        "       sodipodi:nodetypes=\"cccc\"\n"
        "       inkscape:connector-curvature=\"0\"\n"
        "       id=\"path826\"\n"
        "       d=\"m 16.493419,271.04123 c 1.607313,8.06298 11.372592,15.0015 1.098927,17.85758 -4.655516,1.06684 -7.326754,-1.86515 -7.143031,-5.3298 0.590525,-6.80518 3.693926,-8.97119 6.044104,-12.52778 z\"\n"
        "       style=\"fill:#971716;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.307699px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\" />\n"
        "    <path\n"
        "       sodipodi:nodetypes=\"cccc\"\n"
        "       inkscape:connector-curvature=\"0\"\n"
        "       id=\"path843\"\n"
        "       d=\"m 13.106739,279.09507 c -1.400232,2.4726 -1.838461,4.5418 -0.03885,5.67253 1.475395,-0.14407 1.397281,-1.42738 1.359854,-2.68085 -0.655084,-0.35297 -0.963841,-1.74493 -1.321,-2.99168 z\"\n"
        "       style=\"fill:#ffffff;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.307699px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\" />\n"
        "    <g\n"
        "       id=\"g854\"\n"
        "       transform=\"matrix(1.1629599,0,0,1.1629599,-1.6938378,-46.500027)\">\n"
        "      <path\n"
        "         sodipodi:nodetypes=\"cccc\"\n"
        "         inkscape:connector-curvature=\"0\"\n"
        "         id=\"path826-3\"\n"
        "         d=\"m 8.7182705,285.80949 c -0.290487,2.0625 6.8311175,5.62796 0.7936359,8.82152 -1.9952815,0.27689 -3.7319609,-0.81519 -3.6231067,-2.7034 0.2995273,-3.45173 1.6374076,-4.31414 2.8294708,-6.11812 z\"\n"
        "         style=\"fill:#971716;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.15607226px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\" />\n"
        "      <path\n"
        "         sodipodi:nodetypes=\"cccc\"\n"
        "         inkscape:connector-curvature=\"0\"\n"
        "         id=\"path850\"\n"
        "         d=\"m 7.3114769,289.79482 c -0.8447524,1.45414 -0.8465651,2.61606 0,2.68127 0.3341978,0.0508 0.6724551,-0.13161 0.8031995,-0.63784 0.2034406,-0.69646 -0.6016292,-1.34023 -0.8031995,-2.04343 z\"\n"
        "         style=\"fill:#ffffff;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\" />\n"
        "    </g>\n"
        "  </g>\n"
        "</svg>\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


