// automaticly generated by wsjcpp:v0.4.3

#include <wsjcpp_resources_manager.h>

class RES___data_sample_config_yml_path37a5c6 : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename();
        virtual const std::string &getPackAs();
        virtual const int getBufferSize();
        virtual const char *getBuffer();
};


