// automaticly generated by wsjcpp:v0.5.2

#include "__data_sample_html_images_states_place_3st_svg_path8bb9f2.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_images_states_place_3st_svg_path8bb9f2)

const std::string &RES___data_sample_html_images_states_place_3st_svg_path8bb9f2::getFilename() const {
    static const std::string s = "./data_sample/html/images/states/place-3st.svg";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_images_states_place_3st_svg_path8bb9f2::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_images_states_place_3st_svg_path8bb9f2::getBufferSize() const {
    return 5552;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_images_states_place_3st_svg_path8bb9f2::getBuffer() const {
    static const std::string sRet = "" // size: 5552
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->\n"
        "\n"
        "<svg\n"
        "   version=\"1.1\"\n"
        "   id=\"Layer_1\"\n"
        "   x=\"0px\"\n"
        "   y=\"0px\"\n"
        "   width=\"512px\"\n"
        "   height=\"512px\"\n"
        "   viewBox=\"0 0 512 512\"\n"
        "   enable-background=\"new 0 0 512 512\"\n"
        "   xml:space=\"preserve\"\n"
        "   sodipodi:docname=\"place-3st.svg\"\n"
        "   inkscape:version=\"1.1.2 (0a00cf5339, 2022-02-04)\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"><metadata\n"
        "   id=\"metadata13\"><rdf:RDF><cc:Work\n"
        "       rdf:about=\"\"><dc:format>image/svg+xml</dc:format><dc:type\n"
        "         rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" /></cc:Work></rdf:RDF></metadata><defs\n"
        "   id=\"defs11\"><linearGradient\n"
        "     id=\"linearGradient6004\"\n"
        "     inkscape:swatch=\"solid\"><stop\n"
        "       style=\"stop-color:#b1cab1;stop-opacity:1;\"\n"
        "       offset=\"0\"\n"
        "       id=\"stop6002\" /></linearGradient><filter\n"
        "     inkscape:collect=\"always\"\n"
        "     style=\"color-interpolation-filters:sRGB\"\n"
        "     id=\"filter11419\"\n"
        "     x=\"-0.08417406\"\n"
        "     y=\"-0.090899719\"\n"
        "     width=\"1.1683481\"\n"
        "     height=\"1.1817994\"><feGaussianBlur\n"
        "       inkscape:collect=\"always\"\n"
        "       stdDeviation=\"11.681654\"\n"
        "       id=\"feGaussianBlur11421\" /></filter></defs><sodipodi:namedview\n"
        "   pagecolor=\"#000000\"\n"
        "   bordercolor=\"#666666\"\n"
        "   borderopacity=\"1\"\n"
        "   objecttolerance=\"10\"\n"
        "   gridtolerance=\"10\"\n"
        "   guidetolerance=\"10\"\n"
        "   inkscape:pageopacity=\"0\"\n"
        "   inkscape:pageshadow=\"2\"\n"
        "   inkscape:window-width=\"2490\"\n"
        "   inkscape:window-height=\"1376\"\n"
        "   id=\"namedview9\"\n"
        "   showgrid=\"false\"\n"
        "   inkscape:zoom=\"0.11523437\"\n"
        "   inkscape:cx=\"3575.3221\"\n"
        "   inkscape:cy=\"-2156.4746\"\n"
        "   inkscape:window-x=\"70\"\n"
        "   inkscape:window-y=\"27\"\n"
        "   inkscape:window-maximized=\"1\"\n"
        "   inkscape:current-layer=\"Layer_1\"\n"
        "   inkscape:pagecheckerboard=\"0\"\n"
        "   inkscape:snap-global=\"false\" />\n"
        "\n"
        "<path\n"
        "   id=\"path3760\"\n"
        "   style=\"fill:#c26527;fill-opacity:0.63137257;fill-rule:evenodd;stroke:none;stroke-width:1.16773px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "   d=\"m 380.1202,308.57022 c -30.35196,29.40783 -70.90169,49.92504 -121.57533,51.81369 l 45.40404,101.51963 45.28188,-60.60351 77.03566,16.5032 z m -121.57533,51.81369 c -44.90168,-0.19053 -84.60945,-14.7382 -119.07209,-43.78889 l -48.564202,101.10214 79.753262,-14.63466 43.72599,57.63371 z\"\n"
        "   sodipodi:nodetypes=\"cccccccccccc\" /><path\n"
        "   style=\"fill:#c27c27;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:1.20602px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "   d=\"M 267.3727,75.756566 C 170.92284,77.012288 120.21574,133.41785 119.37312,196.605 120.09079,265.58504 175.17494,324.14392 267.3727,324.76876 352.49429,323.39939 399.68458,265.345 400.90158,196.605 398.29111,127.1465 346.06854,77.704783 267.3727,75.756566 Z\"\n"
        "   id=\"path7712\"\n"
        "   sodipodi:nodetypes=\"ccccc\" /><path\n"
        "   id=\"path902-3\"\n"
        "   style=\"fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:1.16773px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1;filter:url(#filter11419)\"\n"
        "   d=\"M 260.50182,51.92995 C 168.42794,52.77181 86.886321,116.38492 88.366151,198.764 89.856251,284.75446 148.33665,361.81385 260.50182,360.33651 356.2062,359.21362 421.70801,285.19154 421.41672,198.764 421.24511,115.06445 348.58512,52.60351 260.50182,51.92995 Z m 0,28.02137 c 81.52741,5.03437 129.17336,54.00754 128.79923,118.81268 -4.80138,84.60589 -54.72346,120.71284 -128.79923,123.48177 -77.45657,-5.78292 -138.63109,-52.52288 -141.1287,-123.48177 1.3808,-59.58475 59.14573,-117.76573 141.1287,-118.81268 z\"\n"
        "   sodipodi:nodetypes=\"cccccccccc\" /><path\n"
        "   id=\"path902\"\n"
        "   style=\"fill:#c26527;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:1.16773px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "   d=\"M 260.50182,51.929953 C 168.42794,52.77181 86.886318,116.38492 88.366148,198.764 89.856248,284.75446 148.33665,361.81385 260.50182,360.33651 356.2062,359.21362 421.70801,285.19154 421.41672,198.764 421.24511,115.06445 348.58512,52.603507 260.50182,51.929953 Z m 0,28.021368 C 342.02923,84.985688 389.67518,133.95886 389.30105,198.764 384.49967,283.36989 334.57759,319.47684 260.50182,322.24577 183.04525,316.46285 121.87073,269.72289 119.37312,198.764 120.75392,139.17925 178.51885,80.998274 260.50182,79.951321 Z\"\n"
        "   sodipodi:nodetypes=\"cccccccccc\" /><path\n"
        "   style=\"fill:#8b4a18;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:4;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1\"\n"
        "   d=\"m 237.96592,222.04404 2.33766,19.75016 c 2.28898,12.37582 24.8832,9.44495 24.43232,-6.89505 l 0.50744,-21.18451 c -5.66868,-12.0271 -15.02008,-11.37297 -23.94033,-12.20346 l -0.52321,-18.61614 c 9.43124,7.1412 16.51887,0.7312 25.81257,-5.19393 l 3.72094,-25.36479 c -0.52332,-11.98325 -29.63491,-13.11568 -32.27882,-3.10625 l -3.08484,14.59734 h -27.71986 c -10.85429,-11.72328 -5.42643,-20.2172 2.5081,-31.5613 9.25412,-12.53067 22.82737,-14.58667 60.63768,-10.96044 51.00948,2.18994 47.87971,54.18371 24.54771,65.78136 28.50974,48.95912 10.7464,91.18512 -45.53315,89.04459 -35.74775,-2.92494 -48.68505,-12.78112 -48.61025,-43.44967 4.11649,-20.71115 17.73238,-12.08042 37.18604,-10.63791 z\"\n"
        "   id=\"path899\"\n"
        "   sodipodi:nodetypes=\"ccccccccccccccccc\" /></svg>\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


