// automaticly generated by wsjcpp:v0.4.3

#include "__data_sample_logs__placeholder_path8997d4.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_logs__placeholder_path8997d4)

const std::string &RES___data_sample_logs__placeholder_path8997d4::getFilename() {
    static const std::string s = "./data_sample/logs/.placeholder";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_logs__placeholder_path8997d4::getPackAs() {
    static const std::string s = "binary";
    return s;
}
// ---------------------------------------------------------------------

const int RES___data_sample_logs__placeholder_path8997d4::getBufferSize() {
    return 0;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_logs__placeholder_path8997d4::getBuffer() {
    static const unsigned char b[0] = {
    };
    return (const char*)b;
} //::buffer() 


