// automaticly generated by wsjcpp:v0.5.2

#include <wsjcpp_core.h>

class RES___data_sample_html_images_first_blood_svg_pathd14a70 : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename() const override;
        virtual const std::string &getPackAs() const override;
        virtual int getBufferSize() const override;
        virtual const char *getBuffer() const override;
};


