// automaticly generated by wsjcpp:v0.5.3

#include "__data_sample_html_images_states_shit_svg_pathb981f7.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_images_states_shit_svg_pathb981f7)

const std::string &RES___data_sample_html_images_states_shit_svg_pathb981f7::getFilename() const {
    static const std::string s = "./data_sample/html/images/states/shit.svg";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_images_states_shit_svg_pathb981f7::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_images_states_shit_svg_pathb981f7::getBufferSize() const {
    return 2770;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_images_states_shit_svg_pathb981f7::getBuffer() const {
    static const std::string sRet = "" // size: 2770
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) by Toomai Glittershine for SmashWiki -->\n"
        "\n"
        "<svg\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   id=\"svg2\"\n"
        "   version=\"1.1\"\n"
        "   height=\"256\"\n"
        "   width=\"256\"\n"
        "   viewBox=\"0 0 256 256\"\n"
        "   sodipodi:docname=\"shit.svg\"\n"
        "   inkscape:version=\"0.92.3 (2405546, 2018-03-11)\">\n"
        "  <defs\n"
        "     id=\"defs8\" />\n"
        "  <sodipodi:namedview\n"
        "     pagecolor=\"#ffffff\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1\"\n"
        "     objecttolerance=\"10\"\n"
        "     gridtolerance=\"10\"\n"
        "     guidetolerance=\"10\"\n"
        "     inkscape:pageopacity=\"0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:window-width=\"1577\"\n"
        "     inkscape:window-height=\"796\"\n"
        "     id=\"namedview6\"\n"
        "     showgrid=\"false\"\n"
        "     inkscape:zoom=\"1.3037281\"\n"
        "     inkscape:cx=\"-34.551654\"\n"
        "     inkscape:cy=\"91.143768\"\n"
        "     inkscape:window-x=\"67\"\n"
        "     inkscape:window-y=\"27\"\n"
        "     inkscape:window-maximized=\"0\"\n"
        "     inkscape:current-layer=\"svg2\" />\n"
        "  <metadata\n"
        "     id=\"metadata7\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "        <dc:title></dc:title>\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <path\n"
        "     style=\"fill:#0400f5;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "     d=\"m 61.737452,122.36758 c -19.180513,12.5062 -44.677646,29.24498 -17.5035,60.95445 44.510723,35.23308 137.842978,24.9914 165.571298,3.58793 39.65425,-23.93113 8.71562,-51.42129 -5.96611,-62.91526 -23.01118,54.87879 -146.988757,31.18468 -142.101688,-1.62712 z\"\n"
        "     id=\"path827\"\n"
        "     inkscape:connector-curvature=\"0\"\n"
        "     sodipodi:nodetypes=\"ccccc\" />\n"
        "  <path\n"
        "     style=\"fill:#0400f5;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "     d=\"m 167.50016,87.113342 c 28.96793,16.391358 35.5038,32.359468 10.30509,47.728818 -27.35901,10.73965 -56.77173,9.8416 -87.190434,3.24295 C 70.907152,128.10797 59.572212,113.1026 77.241607,93.079446 98.888925,77.583052 127.5332,70.541554 136.04253,37.215037 c 24.77845,4.150054 36.45502,60.018899 -12.47457,65.084753 -3.80366,3.68253 -7.79432,8.70669 3.79661,10.84745 20.00577,3.25107 30.12183,-11.29934 40.13559,-26.033898 z\"\n"
        "     id=\"path829\"\n"
        "     inkscape:connector-curvature=\"0\"\n"
        "     sodipodi:nodetypes=\"cccccccc\" />\n"
        "</svg>\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


