// automaticly generated by wsjcpp:v0.5.2

#include "__data_sample_html_images_sla_svg_path59ea65.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_sample_html_images_sla_svg_path59ea65)

const std::string &RES___data_sample_html_images_sla_svg_path59ea65::getFilename() const {
    static const std::string s = "./data_sample/html/images/sla.svg";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_sample_html_images_sla_svg_path59ea65::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_sample_html_images_sla_svg_path59ea65::getBufferSize() const {
    return 2564;
}

// ---------------------------------------------------------------------

const char *RES___data_sample_html_images_sla_svg_path59ea65::getBuffer() const {
    static const std::string sRet = "" // size: 2564
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) -->\n"
        "\n"
        "<svg\n"
        "   width=\"100\"\n"
        "   height=\"100\"\n"
        "   viewBox=\"0 0 26.458333 26.458334\"\n"
        "   version=\"1.1\"\n"
        "   id=\"svg8\"\n"
        "   inkscape:version=\"1.1.2 (0a00cf5339, 2022-02-04)\"\n"
        "   sodipodi:docname=\"sla.svg\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n"
        "  <defs\n"
        "     id=\"defs2\" />\n"
        "  <sodipodi:namedview\n"
        "     id=\"base\"\n"
        "     pagecolor=\"#000000\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1.0\"\n"
        "     inkscape:pageopacity=\"0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:zoom=\"1.979899\"\n"
        "     inkscape:cx=\"117.68277\"\n"
        "     inkscape:cy=\"48.234784\"\n"
        "     inkscape:document-units=\"mm\"\n"
        "     inkscape:current-layer=\"layer1\"\n"
        "     showgrid=\"false\"\n"
        "     units=\"px\"\n"
        "     inkscape:snap-global=\"false\"\n"
        "     inkscape:window-width=\"2490\"\n"
        "     inkscape:window-height=\"1376\"\n"
        "     inkscape:window-x=\"70\"\n"
        "     inkscape:window-y=\"27\"\n"
        "     inkscape:window-maximized=\"1\"\n"
        "     inkscape:pagecheckerboard=\"0\" />\n"
        "  <metadata\n"
        "     id=\"metadata5\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <g\n"
        "     inkscape:label=\"Layer 1\"\n"
        "     inkscape:groupmode=\"layer\"\n"
        "     id=\"layer1\"\n"
        "     transform=\"translate(0,-270.54165)\">\n"
        "    <path\n"
        "       id=\"path1122\"\n"
        "       style=\"fill:#9cb9ea;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.936253px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "       d=\"M 49.425781,7.1796875 C 29.03869,7.2562846 6.4509105,26.49959 6.0898438,48.027344 6.5149427,73.977731 25.567595,91.618457 48.003906,91.402344 71.843208,92.037078 92.097115,76.902214 92.066406,52.017578 92.279685,26.86588 72.805353,7.0754481 49.425781,7.1796875 Z M 35.935547,19.271484 55.769531,42.003906 44.027344,41.939453 44.158203,59.789062 28.119141,73.587891 28.015625,42.005859 16.746094,41.726562 Z M 65.650391,54.822266 82.300781,66.400391 66.246094,81.179688 65.980469,71.238281 35.164062,73.552734 47.779297,61.568359 65.947266,61.316406 Z\"\n"
        "       transform=\"matrix(0.26458333,0,0,0.26458333,0,270.54165)\"\n"
        "       sodipodi:nodetypes=\"ccccccccccccccccccccc\" />\n"
        "  </g>\n"
        "</svg>\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


