// automaticly generated by wsjcpp:v0.4.3

#include "data_sample_html_index_html_path372dab.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES_data_sample_html_index_html_path372dab)

const std::string &RES_data_sample_html_index_html_path372dab::getFilename() {
    static const std::string s = "data_sample/html/index.html";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES_data_sample_html_index_html_path372dab::getPackAs() {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

const int RES_data_sample_html_index_html_path372dab::getBufferSize() {
    return 4691;
}

// ---------------------------------------------------------------------

const char *RES_data_sample_html_index_html_path372dab::getBuffer() {
    static const std::string sRet = "" // size: 4691
        "<html>\n"
        "<head>\n"
        "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />	\n"
        "    <title>ctf01d</title>\n"
        "    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/favicon-32x32.png\">\n"
        "	<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/favicon-16x16.png\">\n"
        "	<link rel=\"stylesheet\" href=\"css/scoreboard.css\">\n"
        "</head>\n"
        "<body>\n"
        "	\n"
        "	<div class=\"ctf01d-tabs\">\n"
        "		<div class=\"ctf01d-tab\" tabcontentid=\"game_details\">Details</div>\n"
        "		<div class=\"ctf01d-tab active\" tabcontentid=\"game_scoreboard\">Scoreboard</div>\n"
        "		<!-- div class=\"ctf01d-tab\" tabcontentid=\"game_activities\">Activities</div -->\n"
        "		<div class=\"ctf01d-tab\" tabcontentid=\"game_rules\">Rules</div>\n"
        "	</div>\n"
        "	<div class=\"ctf01d-tab-content\" id=\"game_details\">\n"
        "		<div class=\"game-name\" id=\"game_name\"></div>\n"
        "		<div class=\"game-time-range\" id=\"game_time_range\"></div>\n"
        "		<hr>\n"
        "		<h3>Scoreboard Legend</h3>\n"
        "		\n"
        "		<p><div class=\"legend service-status down\"></div> - service is down (dead)</p>\n"
        "		<p><div class=\"legend service-status up\"></div> - service is work (up)</p>\n"
        "		<p><div class=\"legend service-status mumble\"></div> - service is mumble (so slow)</p>\n"
        "		<p><div class=\"legend service-status corrupt\"></div> - service is corrupt</p>\n"
        "		<p><div class=\"legend service-status shit\"></div> - checker is shit (developer of checker for service must fix this)</p>\n"
        "		<p><div class=\"legend activity\"><div class=\"activity-icon\"></div></div> - activities (how much try send flags by team)</p>\n"
        "\n"
        "		<hr>\n"
        "		<h3>Flag send</h3>\n"
        "		<p>The flag format must match the regular expression:</p>\n"
        "		<p>\"^[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}$\"</p>\n"
        "\n"
        "		<p>Form for send flag:</p>\n"
        "		<form target=\"_blank\" method=\"GET\" action=\"/flag\">\n"
        "			By Team<select name=\"teamid\" id=\"team_list\"></select>\n"
        "			<input type=\"text\" size=\"36\" placeholder=\"Flag value\" name=\"flag\"> \n"
        "			<button>Send</button><br>\n"
        "		</form>\n"
        "\n"
        "	</div>\n"
        "	<div class=\"ctf01d-tab-content\" id=\"game_rules\">\n"
        "		<h3>1. Basic</h3>\n"
        "		<p>Every flag have a lifetime (default: 1 minute)</p> <!-- TODO get from server -->\n"
        "		<p>Basic cost of stolen flag (default: 10 points)</p> <!-- TODO get from server -->\n"
        "\n"
        "		<h3>2. Acception of flag defence</h3>\n"
        "		<p>Only that flag defence from the service is counted if:</p>\n"
        "		<ul>\n"
        "			<li> the flag was successfully putted to the service</li>\n"
        "			<li>- the flag has existed on the service all the time of it's life</li>\n"
        "			<li>- the flag was not stolen by another team (s)</li>\n"
        "			<li>- And throughout the life of the flag - the service was in UP state</li>\n"
        "		</ul>\n"
        "\n"
        "		<h3>3. Acception of flag attack</h3>\n"
        "\n"
        "		<p>The attack flag counts if:</p>\n"
        "		<ul>\n"
        "			<li>- the flag has the correct format</li>\n"
        "			<li>- the flag does not belong to your team (not from your service)</li>\n"
        "			<li>- a flag from the same type of service as yours, but your service must be in UP state</li>\n"
        "			<li>- the flag is dealt the first time by your team (the same flag may be dealt by different teams)</li>\n"
        "			<li>- the flag is still alive (the flag has not expired)</li>\n"
        "			<li>- only during the announced game (flags are not accepted during coffeebreaking)</li>\n"
        "		</ul>\n"
        "\n"
        "		<h3>4. How to calculate costs of the flags</h3>\n"
        "		<ul>\n"
        "			<li>- The cost is different for the defended flag and the stolen flag (difference in the number of teams)</li>\n"
        "			<li>- Redistribute the cost for flags between services - depending on the number of passed and defended flags</li>\n"
        "			<li>- The cost of flags should not depend on the \"place\" in the scoreboard table</li>\n"
        "			<li>- The cost of the flags should be different as services may have different times between flag throws</li>\n"
        "			<li>- The cost of flags should be different since the complexity of the services is different</li>\n"
        "		</ul>\n"
        "\n"
        "		<h3>5. How to calculate of team score</h3>\n"
        "		<p>Sum by score services, for each:</p>\n"
        "		<p>(<div class=\"d-icn att\"></div> + <div class=\"d-icn def\"></div>), </p>\n"
        "		<p>where:</p>\n"
        "		\n"
        "		<ul style=\"display: inline-block; text-align: left\">\n"
        "			<li>\n"
        "				<div class=\"d-icn def\"></div> - the number of defended flags\n"
        "			</li>\n"
        "			<li>\n"
        "				<div class=\"d-icn att\"></div> - the number of stolen flags\n"
        "			</li>\n"
        "		</ul>\n"
        "		<div class=\"game-rule-header\">4. Issues for a jury system</div>\n"
        "		<div class=\"game-rule\">\n"
        "			<a target=\"_blank\" href=\"https://github.com/freehackquest/ctf01d/issues\">https://github.com/freehackquest/ctf01d/issues</a>\n"
        "		</div>\n"
        "	</div>\n"
        "	<div class=\"ctf01d-tab-content\" id=\"game_scoreboard\" style=\"display: block\">\n"
        "		<div id=\"scoreboard_content\" style=\"display: none\">\n"
        "		\n"
        "		</div>\n"
        "		<div id=\"loader_content\" style=\"display: block\">\n"
        "			<div class=\"lds-facebook\">\n"
        "				<div></div>\n"
        "				<div></div>\n"
        "				<div></div>\n"
        "			</div>\n"
        "		</div>\n"
        "	</div>\n"
        "<script src=\"js/scoreboard.js\" defer=\"defer\"></script>\n"
        "</body>\n"
        "</html>\n"
        "\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


