# First run
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && docker-compose up -d && docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8080

version: '3'
services:
  dockovpn:
    image: sea5kg/ctf01d-openvpn:v0.4.4
    ports:
        - 1194:1194/udp
    volumes:
        - ./ctf01d_openvpn_conf:/etc/ctf01d-openvpn
    restart: always
