// automaticly generated by update_resources.py


#include <wsjcpp_resources_manager.h>

class RES_html_js_scoreboard_js : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename();
        virtual const std::string &getPackAs();
        virtual const int getBufferSize();
        virtual const char *getBuffer();
};

