// automaticly generated by update_resources.py

#include <html_images_uptime_svg.h>

REGISTRY_WSJCPP_RESOURCE_FILE(RES_html_images_uptime_svg)

const std::string &RES_html_images_uptime_svg::getFilename() {
    static const std::string s = "html/images/uptime.svg";
    return s;
}

const std::string &RES_html_images_uptime_svg::getPackAs() {
    static const std::string s = "binary";
    return s;
}

const int RES_html_images_uptime_svg::getBufferSize() {
    return 3581;
}

const char *RES_html_images_uptime_svg::getBuffer() {
    static const std::string sRet =  // size: 3581
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) -->\n"
        "\n"
        "<svg\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   width=\"100\"\n"
        "   height=\"100\"\n"
        "   viewBox=\"0 0 26.458333 26.458334\"\n"
        "   version=\"1.1\"\n"
        "   id=\"svg8\"\n"
        "   inkscape:version=\"0.92.3 (2405546, 2018-03-11)\"\n"
        "   sodipodi:docname=\"uptime.svg\">\n"
        "  <defs\n"
        "     id=\"defs2\" />\n"
        "  <sodipodi:namedview\n"
        "     id=\"base\"\n"
        "     pagecolor=\"#ffffff\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1.0\"\n"
        "     inkscape:pageopacity=\"0.0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:zoom=\"2.8\"\n"
        "     inkscape:cx=\"-43.7796\"\n"
        "     inkscape:cy=\"48.59797\"\n"
        "     inkscape:document-units=\"px\"\n"
        "     inkscape:current-layer=\"layer1\"\n"
        "     showgrid=\"false\"\n"
        "     units=\"px\"\n"
        "     inkscape:window-width=\"1853\"\n"
        "     inkscape:window-height=\"1025\"\n"
        "     inkscape:window-x=\"67\"\n"
        "     inkscape:window-y=\"27\"\n"
        "     inkscape:window-maximized=\"1\"\n"
        "     inkscape:snap-global=\"false\" />\n"
        "  <metadata\n"
        "     id=\"metadata5\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "        <dc:title></dc:title>\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <g\n"
        "     inkscape:label=\"Layer 1\"\n"
        "     inkscape:groupmode=\"layer\"\n"
        "     id=\"layer1\"\n"
        "     transform=\"translate(0,-270.54166)\">\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-3\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-1\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <path\n"
        "       style=\"opacity:1;fill:#fffffe;fill-opacity:1;stroke:#000000;stroke-width:0.26458332;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;paint-order:normal\"\n"
        "       d=\"m 17.144937,292.73005 c -1.326658,0.71939 -2.76941,0.99263 -4.370745,0.99262 -5.2905921,-2.6e-4 -9.5793165,-4.44191 -9.5792595,-9.92084 -5.7e-5,-5.47893 4.2886674,-9.92058 9.5792595,-9.92084 4.168875,-3e-5 7.749207,2.65745 9.065981,6.50744 l 3.632295,-0.97183 c -1.768908,-5.17395 -6.629687,-8.7428 -12.390284,-8.74265 -7.2512125,1e-4 -13.12942834,5.89336 -13.12943054,13.16302 2.2e-6,7.26966 5.87821804,13.16292 13.12943054,13.16302 1.42805,4e-5 2.802856,-0.2285 4.090004,-0.6511 z\"\n"
        "       id=\"path845\"\n"
        "       inkscape:connector-curvature=\"0\"\n"
        "       sodipodi:nodetypes=\"cccccccsccc\" />\n"
        "    <path\n"
        "       style=\"fill:#ffffff;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "       d=\"m 8.9881099,288.02503 2.7427021,2.12443 4.167811,-4.77223 -0.02362,-7.40284 -3.998105,-0.0115 0.07661,6.02052 z\"\n"
        "       id=\"path850\"\n"
        "       inkscape:connector-curvature=\"0\"\n"
        "       sodipodi:nodetypes=\"ccccccc\" />\n"
        "    <path\n"
        "       style=\"fill:#fffffe;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "       d=\"m 20.363468,295.93693 5.480653,5e-5 -1.285673,-3.14164 -0.273485,-6.33139 1.700893,0.23619 -2.976563,-5.00818 -2.929315,5.43341 1.74814,-0.66141 -0.05786,6.16602 z\"\n"
        "       id=\"path852\"\n"
        "       inkscape:connector-curvature=\"0\"\n"
        "       sodipodi:nodetypes=\"cccccccccc\" />\n"
        "  </g>\n"
        "</svg>\n"
    ;
    return sRet.c_str();
} //::buffer() 

