## Combined config for ctf01d
# use 2 spaces for tab

game:
  id: "test" # uniq gameid must be regexp [a-z0-9]+
  name: "Test First Game" # visible game name in scoreboard
  start: "2023-11-12 16:00:00" # start time of game (UTC)
  end: "2030-11-12 22:00:00" # end time of game (UTC)
  coffee_break_start: "2023-11-12 20:00:00" # start time of game coffee break (UTC), but it will be ignored if period more (or less) then start and end
  coffee_break_end: "2023-11-12 21:00:00" # end time of game coffee break (UTC), but it will be ignored if period more (or less) then start and end
  flag_timelive_in_min: 1 # you can change flag time live (in minutes)
  basic_costs_stolen_flag_in_points: 10 # basic costs stolen (attack) flag in points for adaptive scoreboard

server:
  # use storage which storage will be used, now possible values:
  # mysql - use mysql database
  # ram - (!not implemented yet) use just memory
  # local - (!not implemented yet) use just memory
  # postgres - (!not implemented yet) will be used postgre database
  use_storage: mysql

scoreboard:
  port: 8080 # http port for scoreboard
  htmlfolder: "./html" # web page for scoreboard see index-template.html
  random: no # If yes - will be random values in scoreboard

mysql_storage: # if server.use_storage is mysql
  dbhost: "ctf01d_db"
  dbport: 3306
  dbname: "ctf01d"
  dbuser: "ctf01d"
  dbpass: "ctf01d"

checkers:
  - id: "example_service1" # work directory will be checker_example_service4
    service_name: "Service1"
    enabled: yes
    # host: 127.0.0.1
    # port: 10001
    script_path: "./checker.py"
    script_wait_in_sec: 5 # max time for running script
    time_sleep_between_run_scripts_in_sec: 15 # like a round for service
  - id: "example_service2" # work directory will be checker_example_service4
    service_name: "Service2"
    enabled: yes
    script_path: "./checker.py"
    script_wait_in_sec: 5
    time_sleep_between_run_scripts_in_sec: 15
  - id: "example_service3" # work directory will be checker_example_service4
    service_name: "Service3"
    enabled: yes
    script_path: "./checker.py"
    script_wait_in_sec: 5
    time_sleep_between_run_scripts_in_sec: 15
  - id: "example_service4" # work directory will be checker_example_service4
    service_name: "Service4"
    enabled: yes
    script_path: "./checker.py"
    script_wait_in_sec: 5
    time_sleep_between_run_scripts_in_sec: 15

teams:
  - id: "t01" # must be uniq
    name: "Team #1"
    active: yes
    logo: "./html/images/teams/team01.png"
    ip_address: "127.0.1.1" # address to vulnserver
  - id: "t02" # must be uniq
    name: "Team #2"
    active: yes
    logo: "./html/images/teams/team02.png"
    ip_address: "127.0.2.1" # address to vulnserver
  - id: "t03" # must be uniq
    name: "Team #3"
    active: yes
    logo: "./html/images/teams/team03.png"
    ip_address: "127.0.3.1" # address to vulnserver
  - id: "t04" # must be uniq
    name: "Team #4"
    active: yes
    logo: "./html/images/teams/team04.png"
    ip_address: "127.0.3.1" # address to vulnserver
  - id: "t05" # must be uniq
    name: "Team #5"
    active: yes
    logo: "./html/images/teams/team05.png"
    ip_address: "127.0.5.1" # address to vulnserver
  - id: "t06" # must be uniq
    name: "Team #6"
    active: yes
    logo: "./html/images/teams/team06.png"
    ip_address: "127.0.6.1" # address to vulnserver
  - id: "t07" # must be uniq
    name: "Team #7"
    active: yes
    logo: "./html/images/teams/team07.png"
    ip_address: "127.0.7.1" # address to vulnserver
  - id: "t08" # must be uniq
    name: "Team #8"
    active: yes
    logo: "./html/images/teams/team08.png"
    ip_address: "127.0.8.1" # address to vulnserver
  - id: "t09" # must be uniq
    name: "Team #9"
    active: yes
    logo: "./html/images/teams/team09.png"
    ip_address: "127.0.9.1" # address to vulnserver
  - id: "t10" # must be uniq
    name: "Team #10"
    active: yes
    logo: "./html/images/teams/team10.png"
    ip_address: "127.0.10.1" # address to vulnserver
  - id: "t11" # must be uniq
    name: "Team #11"
    active: yes
    logo: "./html/images/teams/team11.png"
    ip_address: "127.0.11.1" # address to vulnserver
  - id: "t12" # must be uniq
    name: "Team #12"
    active: yes
    logo: "./html/images/teams/team12.png"
    ip_address: "127.0.12.1" # address to vulnserver
  - id: "t13" # must be uniq
    name: "Team #13"
    active: yes
    logo: "./html/images/teams/team13.png"
    ip_address: "127.0.13.1" # address to vulnserver
  - id: "t14" # must be uniq
    name: "Team #14"
    active: yes
    logo: "./html/images/teams/team14.png"
    ip_address: "127.0.14.1" # address to vulnserver
  - id: "t15" # must be uniq
    name: "Team #15"
    active: yes
    logo: "./html/images/teams/team15.png"
    ip_address: "127.0.15.1" # address to vulnserver
  - id: "t16" # must be uniq
    name: "Team #16"
    active: yes
    logo: "./html/images/teams/team16.png"
    ip_address: "127.0.16.1" # address to vulnserver
  - id: "t17" # must be uniq
    name: "Team #17"
    active: yes
    logo: "./html/images/teams/team17.png"
    ip_address: "127.0.17.1" # address to vulnserver
  - id: "t18" # must be uniq
    name: "Team #18"
    active: yes
    logo: "./html/images/teams/team18.png"
    ip_address: "127.0.18.1" # address to vulnserver
  - id: "t19" # must be uniq
    name: "Team #19"
    active: yes
    logo: "./html/images/teams/team19.png"
    ip_address: "127.0.19.1" # address to vulnserver
  - id: "t20" # must be uniq
    name: "Team #20"
    active: yes
    logo: "./html/images/teams/team20.png"
    ip_address: "127.0.20.1" # address to vulnserver
