// automaticly generated by update_resources.py


#include <wsjcpp_resources_manager.h>

class RES_checker_example_service1_checker_py : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename();
        virtual const std::string &getPackAs();
        virtual const int getBufferSize();
        virtual const char *getBuffer();
};

