// automaticly generated by update_resources.py

#include <html_images_defence_svg.h>

REGISTRY_WSJCPP_RESOURCE_FILE(RES_html_images_defence_svg)

const std::string &RES_html_images_defence_svg::getFilename() {
    static const std::string s = "html/images/defence.svg";
    return s;
}

const int RES_html_images_defence_svg::getBufferSize() {
    return 2922;
}

const char *RES_html_images_defence_svg::getBuffer() {
    static const std::string sRet =  // size: 2922
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) -->\n"
        "\n"
        "<svg\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   width=\"100\"\n"
        "   height=\"100\"\n"
        "   viewBox=\"0 0 26.458333 26.458334\"\n"
        "   version=\"1.1\"\n"
        "   id=\"svg8\"\n"
        "   inkscape:version=\"0.92.3 (2405546, 2018-03-11)\"\n"
        "   sodipodi:docname=\"defence.svg\">\n"
        "  <defs\n"
        "     id=\"defs2\" />\n"
        "  <sodipodi:namedview\n"
        "     id=\"base\"\n"
        "     pagecolor=\"#ffffff\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1.0\"\n"
        "     inkscape:pageopacity=\"0.0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:zoom=\"2.8\"\n"
        "     inkscape:cx=\"89.372816\"\n"
        "     inkscape:cy=\"17.615744\"\n"
        "     inkscape:document-units=\"px\"\n"
        "     inkscape:current-layer=\"layer1\"\n"
        "     showgrid=\"false\"\n"
        "     units=\"px\"\n"
        "     inkscape:window-width=\"1853\"\n"
        "     inkscape:window-height=\"1025\"\n"
        "     inkscape:window-x=\"67\"\n"
        "     inkscape:window-y=\"27\"\n"
        "     inkscape:window-maximized=\"1\"\n"
        "     inkscape:snap-global=\"false\" />\n"
        "  <metadata\n"
        "     id=\"metadata5\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "        <dc:title></dc:title>\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <g\n"
        "     inkscape:label=\"Layer 1\"\n"
        "     inkscape:groupmode=\"layer\"\n"
        "     id=\"layer1\"\n"
        "     transform=\"translate(0,-270.54166)\">\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-3\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <g\n"
        "       transform=\"translate(0,-198.96085)\"\n"
        "       id=\"layer1-1\"\n"
        "       inkscape:label=\"Layer 1\" />\n"
        "    <path\n"
        "       style=\"fill:#00b100;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.39925796px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "       d=\"m 12.754248,270.73943 0.07564,6.95739 -0.503752,-0.0756 v 2.29418 l -1.613407,-0.0257 v -2.24349 l -1.9159703,-0.025 0.025733,2.29419 -1.6391412,-0.10142 -0.024954,-2.09222 -1.8403296,-0.025 -0.1005947,6.30157 2.2185327,0.0507 -2.2692198,12.55323 16.0826099,0.0499 -2.117939,-12.60313 1.91597,-0.0257 0.151282,-6.30158 -1.714003,-0.025 -0.02495,2.16785 -1.815377,-0.0756 0.07563,-2.0922 -1.814597,-0.0507 -0.02573,2.29417 h -1.714003 l -0.04991,-2.31913 -0.403157,-0.025 -0.08613,-2.7683 c 2.308887,1.73553 4.723296,-1.47062 7.650089,0.62095 l 0.0025,-4.02348 c -2.517407,-1.04274 -6.075493,1.16429 -7.541537,-0.68596 z m 0.554438,15.45176 2.067252,1.66408 -0.07564,4.08305 -4.10877,-0.025 -0.05069,-4.13372 z\"\n"
        "       id=\"path857\"\n"
        "       inkscape:connector-curvature=\"0\"\n"
        "       sodipodi:nodetypes=\"cccccccccccccccccccccccccccccccccccccc\" />\n"
        "  </g>\n"
        "</svg>\n"
    ;
    return sRet.c_str();
} //::buffer() 

