// automaticly generated by update_resources.py

#include <html_images_states_down_svg.h>

REGISTRY_WSJCPP_RESOURCE_FILE(RES_html_images_states_down_svg)

const std::string &RES_html_images_states_down_svg::getFilename() {
    static const std::string s = "html/images/states/down.svg";
    return s;
}

const std::string &RES_html_images_states_down_svg::getPackAs() {
    static const std::string s = "binary";
    return s;
}

const int RES_html_images_states_down_svg::getBufferSize() {
    return 2864;
}

const char *RES_html_images_states_down_svg::getBuffer() {
    static const std::string sRet =  // size: 2864
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) -->\n"
        "\n"
        "<svg\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   width=\"300\"\n"
        "   height=\"300\"\n"
        "   viewBox=\"0 0 79.374998 79.375002\"\n"
        "   version=\"1.1\"\n"
        "   id=\"svg8\"\n"
        "   inkscape:version=\"0.92.2 (5c3e80d, 2017-08-06)\"\n"
        "   sodipodi:docname=\"down.svg\">\n"
        "  <defs\n"
        "     id=\"defs2\" />\n"
        "  <sodipodi:namedview\n"
        "     id=\"base\"\n"
        "     pagecolor=\"#000000\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1.0\"\n"
        "     inkscape:pageopacity=\"0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:zoom=\"0.7\"\n"
        "     inkscape:cx=\"208.34919\"\n"
        "     inkscape:cy=\"123.97809\"\n"
        "     inkscape:document-units=\"mm\"\n"
        "     inkscape:current-layer=\"layer1\"\n"
        "     showgrid=\"false\"\n"
        "     units=\"px\"\n"
        "     inkscape:window-width=\"1853\"\n"
        "     inkscape:window-height=\"1025\"\n"
        "     inkscape:window-x=\"67\"\n"
        "     inkscape:window-y=\"27\"\n"
        "     inkscape:window-maximized=\"1\" />\n"
        "  <metadata\n"
        "     id=\"metadata5\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "        <dc:title></dc:title>\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <g\n"
        "     inkscape:label=\"Layer 1\"\n"
        "     inkscape:groupmode=\"layer\"\n"
        "     id=\"layer1\"\n"
        "     transform=\"translate(0,-217.62498)\">\n"
        "    <path\n"
        "       style=\"fill:#de1500;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:0.99999994px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "       d=\"M 151.35547 57.015625 C 149.55897 56.97751 147.79559 57.018819 146.07227 57.142578 C 69.005499 62.310629 12.148506 157.22025 93.572266 217.14258 L 93.339844 244.33594 L 114.11914 245.13086 L 112.85742 227.14258 L 122.5 228.21484 L 122.12109 244.8125 L 142.5 245.19141 L 142.14258 227.85742 L 151.07227 227.5 L 151.57617 244.93945 L 170.71484 244.64258 L 170.71484 227.5 L 179.64258 227.5 L 181.07227 244.64258 L 200.80078 244.87305 L 200.80078 216.66016 C 294.4666 135.97193 207.04689 58.197198 151.35547 57.015625 z M 153.29102 155.29492 L 224.50586 155.80078 C 222.35043 175.5956 213.14321 189.24799 190.16211 190.9043 C 171.33927 190.84496 156.06655 184.12512 153.29102 155.29492 z M 69.195312 155.80078 L 141.42188 156.30664 C 139.27936 177.48999 127.65414 191.85918 105.05664 191.91406 C 78.35974 190.05336 73.959604 171.75984 69.195312 155.80078 z M 146.97656 181.05469 L 166.42188 200.75195 L 128.03711 200.75195 L 146.97656 181.05469 z \"\n"
        "       transform=\"matrix(0.26458333,0,0,0.26458333,0,217.62498)\"\n"
        "       id=\"path826\" />\n"
        "  </g>\n"
        "</svg>\n"
    ;
    return sRet.c_str();
} //::buffer() 

