// automaticly generated by update_resources.py


#include <wsjcpp_resources_manager.h>

class RES_html_images_first_blood_svg : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename();
        virtual const int getBufferSize();
        virtual const char *getBuffer();
};

