// automaticly generated by update_resources.py

#include <html_images_states_corrupt_svg.h>

REGISTRY_WSJCPP_RESOURCE_FILE(RES_html_images_states_corrupt_svg)

const std::string &RES_html_images_states_corrupt_svg::getFilename() {
    static const std::string s = "html/images/states/corrupt.svg";
    return s;
}

const std::string &RES_html_images_states_corrupt_svg::getPackAs() {
    static const std::string s = "binary";
    return s;
}

const int RES_html_images_states_corrupt_svg::getBufferSize() {
    return 3462;
}

const char *RES_html_images_states_corrupt_svg::getBuffer() {
    static const std::string sRet =  // size: 3462
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) by Toomai Glittershine for SmashWiki -->\n"
        "\n"
        "<svg\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   id=\"svg2\"\n"
        "   version=\"1.1\"\n"
        "   height=\"256\"\n"
        "   width=\"256\"\n"
        "   viewBox=\"0 0 256 256\"\n"
        "   sodipodi:docname=\"currupt.svg\"\n"
        "   inkscape:version=\"0.92.2 (5c3e80d, 2017-08-06)\">\n"
        "  <defs\n"
        "     id=\"defs8\" />\n"
        "  <sodipodi:namedview\n"
        "     pagecolor=\"#ffffff\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1\"\n"
        "     objecttolerance=\"10\"\n"
        "     gridtolerance=\"10\"\n"
        "     guidetolerance=\"10\"\n"
        "     inkscape:pageopacity=\"0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:window-width=\"1577\"\n"
        "     inkscape:window-height=\"796\"\n"
        "     id=\"namedview6\"\n"
        "     showgrid=\"false\"\n"
        "     inkscape:zoom=\"0.921875\"\n"
        "     inkscape:cx=\"128\"\n"
        "     inkscape:cy=\"128\"\n"
        "     inkscape:window-x=\"67\"\n"
        "     inkscape:window-y=\"27\"\n"
        "     inkscape:window-maximized=\"0\"\n"
        "     inkscape:current-layer=\"svg2\" />\n"
        "  <g\n"
        "     id=\"setting\"\n"
        "     style=\"fill:#f2de00;fill-opacity:1;stroke:#00e200;stroke-opacity:1\">\n"
        "    <animateTransform\n"
        "       attributeName=\"transform\"\n"
        "       attributeType=\"XML\"\n"
        "       type=\"rotate\"\n"
        "       from=\"0 128 128\"\n"
        "       to=\"360 128 128\"\n"
        "       dur=\"8s\"\n"
        "       repeatCount=\"indefinite\" />\n"
        "    <path\n"
        "       id=\"mainsymbolpath\"\n"
        "       style=\"opacity:1;fill:#f2de00;fill-opacity:1;stroke:#00e200;stroke-opacity:1\"\n"
        "       d=\"m 121.21875,37.84375 -3.4375,9.5 -1.75,9.59375 c -4.56422,0.763494 -8.98805,1.921834 -13.21875,3.5 l -6.28125,-7.375 -7.75,-6.53125 -11.71875,6.78125 1.78125,9.9375 3.21875,9.15625 c -3.522603,2.912618 -6.743632,6.133647 -9.65625,9.65625 L 63.25,78.84375 53.3125,77.0625 l -6.78125,11.71875 6.53125,7.75 7.375,6.28125 c -1.578166,4.2307 -2.736506,8.65453 -3.5,13.21875 l -9.59375,1.75 -9.5,3.4375 0,13.5625 9.5,3.4375 9.59375,1.75 c 0.763494,4.56422 1.921834,8.98805 3.5,13.21875 l -7.375,6.28125 -6.53125,7.75 6.78125,11.71875 9.9375,-1.78125 9.15625,-3.21875 c 2.912618,3.5226 6.133647,6.74363 9.65625,9.65625 l -3.21875,9.15625 -1.78125,9.9375 11.71875,6.78125 7.75,-6.53125 6.28125,-7.375 c 4.2307,1.57817 8.65453,2.73651 13.21875,3.5 l 1.75,9.59375 3.4375,9.5 13.5625,0 3.4375,-9.5 1.75,-9.59375 c 4.56422,-0.76349 8.98805,-1.92183 13.21875,-3.5 l 6.28125,7.375 7.75,6.53125 11.71875,-6.78125 -1.78125,-9.9375 -3.21875,-9.15625 c 3.5226,-2.91262 6.74363,-6.13365 9.65625,-9.65625 l 9.15625,3.21875 9.9375,1.78125 6.78125,-11.71875 -6.53125,-7.75 -7.375,-6.28125 c 1.57817,-4.2307 2.73651,-8.65453 3.5,-13.21875 l 9.59375,-1.75 9.5,-3.4375 0,-13.5625 -9.5,-3.4375 -9.59375,-1.75 c -0.76349,-4.56422 -1.92183,-8.98805 -3.5,-13.21875 l 7.375,-6.28125 6.53125,-7.75 -6.78125,-11.71875 -9.9375,1.78125 -9.15625,3.21875 c -2.91262,-3.522603 -6.13365,-6.743632 -9.65625,-9.65625 l 3.21875,-9.15625 1.78125,-9.9375 -11.71875,-6.78125 -7.75,6.53125 -6.28125,7.375 c -4.2307,-1.578166 -8.65453,-2.736506 -13.21875,-3.5 l -1.75,-9.59375 -3.4375,-9.5 -13.5625,0 z M 128,107.125 c 11.52306,0 20.875,9.35194 20.875,20.875 0,11.52306 -9.35194,20.875 -20.875,20.875 -11.52306,0 -20.875,-9.35194 -20.875,-20.875 0,-11.52306 9.35194,-20.875 20.875,-20.875 z\" />\n"
        "  </g>\n"
        "</svg>\n"
    ;
    return sRet.c_str();
} //::buffer() 

