// automaticly generated by update_resources.py

#include <mysql_storage_conf.h>

REGISTRY_WSJCPP_RESOURCE_FILE(RES_mysql_storage_conf)

const std::string &RES_mysql_storage_conf::getFilename() {
    static const std::string s = "mysql_storage.conf";
    return s;
}

const int RES_mysql_storage_conf::getBufferSize() {
    return 194;
}

const char *RES_mysql_storage_conf::getBuffer() {
    static const std::string sRet =  // size: 194
        "\n"
        "# if server.use_storage is mysql\n"
        "mysql_storage.dbhost = localhost\n"
        "mysql_storage.dbport = 3306\n"
        "mysql_storage.dbname = fhqjuryad\n"
        "mysql_storage.dbuser = fhqjuryad\n"
        "mysql_storage.dbpass = fhqjuryad\n"
    ;
    return sRet.c_str();
} //::buffer() 

