// automaticly generated by update_resources.py

#include <scoreboard_conf.h>

REGISTRY_WSJCPP_RESOURCE_FILE(RES_scoreboard_conf)

const std::string &RES_scoreboard_conf::getFilename() {
    static const std::string s = "scoreboard.conf";
    return s;
}

const int RES_scoreboard_conf::getBufferSize() {
    return 204;
}

const char *RES_scoreboard_conf::getBuffer() {
    static const std::string sRet =  // size: 204
        "\n"
        "# http port for scoreboard\n"
        "scoreboard.port = 8080\n"
        "\n"
        "# web page for scoreboard see index-template.html\n"
        "scoreboard.htmlfolder = ./html\n"
        "\n"
        "# If yes - will be random values in scoreboard\n"
        "scoreboard.random = no\n"
    ;
    return sRet.c_str();
} //::buffer() 

