// automaticly generated by update_resources.py

#include <game_conf.h>

REGISTRY_RESOURCE_FILE(RES_game_conf)

const std::string &RES_game_conf::filename() {
    static const std::string s = "game.conf";
    return s;
}

const int RES_game_conf::bufferSize() {
    return 625;
}

const char *RES_game_conf::buffer() {
    static const std::string sRet =  // size: 625
        "# uniq gameid must be regexp [a-z0-9]+\n"
        "game.id = test\n"
        "\n"
        "# visible game name in scoreboard\n"
        "game.name = Test First Game\n"
        "\n"
        "# start time of game (UTC)\n"
        "game.start = 2019-01-04 10:30:00\n"
        "\n"
        "# end time of game (UTC)\n"
        "game.end = 2030-09-06 13:00:00\n"
        "\n"
        "# start time of game coffee break (UTC)\n"
        "# will be ignored if period more (or less) then game.start and game end\n"
        "game.coffee_break_start = 2020-01-04 10:30:00\n"
        "\n"
        "# end time of game coffee break (UTC)\n"
        "# will be ignored if period more (or less) then game.start and game end\n"
        "game.coffee_break_end = 2021-01-04 10:30:00\n"
        "\n"
        "# you can change flag time live (in minutes)\n"
        "game.flag_timelive_in_min = 1\n"
    ;
    return sRet.c_str();
} //::buffer() 

