// automaticly generated by update_resources.py

#include <html_images_states_mumble_svg.h>

REGISTRY_RESOURCE_FILE(RES_html_images_states_mumble_svg)

const std::string &RES_html_images_states_mumble_svg::filename() {
    static const std::string s = "html/images/states/mumble.svg";
    return s;
}

const int RES_html_images_states_mumble_svg::bufferSize() {
    return 3205;
}

const char *RES_html_images_states_mumble_svg::buffer() {
    static const std::string sRet =  // size: 3205
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) by Toomai Glittershine for SmashWiki -->\n"
        "\n"
        "<svg\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   id=\"svg2\"\n"
        "   version=\"1.1\"\n"
        "   height=\"256\"\n"
        "   width=\"256\"\n"
        "   viewBox=\"0 0 256 256\"\n"
        "   sodipodi:docname=\"mumble.svg\"\n"
        "   inkscape:version=\"0.92.3 (2405546, 2018-03-11)\">\n"
        "  <defs\n"
        "     id=\"defs8\" />\n"
        "  <sodipodi:namedview\n"
        "     pagecolor=\"#ffffff\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1\"\n"
        "     objecttolerance=\"10\"\n"
        "     gridtolerance=\"10\"\n"
        "     guidetolerance=\"10\"\n"
        "     inkscape:pageopacity=\"0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:window-width=\"1577\"\n"
        "     inkscape:window-height=\"796\"\n"
        "     id=\"namedview6\"\n"
        "     showgrid=\"false\"\n"
        "     inkscape:zoom=\"0.46093749\"\n"
        "     inkscape:cx=\"12.993576\"\n"
        "     inkscape:cy=\"306.45253\"\n"
        "     inkscape:window-x=\"145\"\n"
        "     inkscape:window-y=\"56\"\n"
        "     inkscape:window-maximized=\"0\"\n"
        "     inkscape:current-layer=\"svg2\" />\n"
        "  <metadata\n"
        "     id=\"metadata7\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "        <dc:title></dc:title>\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <path\n"
        "     style=\"opacity:1;fill:#d3868c;fill-opacity:1;stroke:none;stroke-width:2.76082492;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;paint-order:normal\"\n"
        "     d=\"m 126.33391,47.458251 c -60.616838,3e-6 -109.756507,35.936307 -109.756562,80.266009 3.9e-5,44.32971 49.139713,80.26603 109.756562,80.26603 60.61685,0 109.75653,-35.93632 109.75657,-80.26603 -6e-5,-44.329704 -49.13973,-80.266009 -109.75657,-80.266009 z m -1.94468,28.057426 c 12.27513,0.02511 24.09571,5.265978 33.12716,14.687535 -9.80153,-5.026083 -18.86638,-3.402274 -29.71864,-3.173783 7.46912,23.150741 -17.18156,24.007041 -0.0595,41.316411 l 7.66986,0.17746 0.22913,45.65969 c -3.72753,1.49326 -3.74671,6.45821 2.03418,6.95145 5.20848,-0.31248 5.0973,-5.37726 1.30166,-7.41699 V 128.4344 l 13.71946,-0.0886 v 32.14177 c -4.21496,1.50271 -3.3593,6.76783 1.58915,6.87375 5.52839,0.42706 5.6592,-5.87067 1.65176,-6.78486 V 128.7007 l 12.63955,-0.17745 0.32407,16.15961 c -1.68764,0.21373 -3.42359,0.85836 -3.24091,3.37421 0.37111,3.26858 1.92655,4.3868 3.90828,4.29643 -5.71398,24.31543 -22.97201,34.29616 -45.17523,34.32713 -27.086606,-1.1e-4 -49.044587,-24.8852 -49.044591,-55.58248 7e-6,-30.69728 21.957988,-55.582362 49.044591,-55.582473 z m 48.0728,52.918723 0.89164,0.0863 c 0.0444,0.85832 0.0713,1.71768 0.0805,2.57741 -0.0113,4.01333 -0.40613,8.01346 -1.17755,11.93043 z m -82.887919,0.76514 c -0.850146,11.56911 20.289049,12.1319 19.860499,0.25132 z\"\n"
        "     id=\"path828\"\n"
        "     inkscape:connector-curvature=\"0\"\n"
        "     sodipodi:nodetypes=\"scscscccccccccccccccccccsccccccccc\" />\n"
        "</svg>\n"
    ;
    return sRet.c_str();
} //::buffer() 

