// automaticly generated by update_resources.py

#include <html_images_states_wait_svg.h>

REGISTRY_RESOURCE_FILE(RES_html_images_states_wait_svg)

const std::string &RES_html_images_states_wait_svg::filename() {
    static const std::string s = "html/images/states/wait.svg";
    return s;
}

const int RES_html_images_states_wait_svg::bufferSize() {
    return 2916;
}

const char *RES_html_images_states_wait_svg::buffer() {
    static const std::string sRet =  // size: 2916
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<!-- Created with Inkscape (http://www.inkscape.org/) by Toomai Glittershine for SmashWiki -->\n"
        "\n"
        "<svg\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   id=\"svg2\"\n"
        "   version=\"1.1\"\n"
        "   height=\"256\"\n"
        "   width=\"256\"\n"
        "   viewBox=\"0 0 256 256\"\n"
        "   sodipodi:docname=\"wait.svg\"\n"
        "   inkscape:version=\"0.92.3 (2405546, 2018-03-11)\">\n"
        "  <defs\n"
        "     id=\"defs8\" />\n"
        "  <sodipodi:namedview\n"
        "     pagecolor=\"#000000\"\n"
        "     bordercolor=\"#665666\"\n"
        "     borderopacity=\"1\"\n"
        "     objecttolerance=\"10\"\n"
        "     gridtolerance=\"10\"\n"
        "     guidetolerance=\"10\"\n"
        "     inkscape:pageopacity=\"0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:window-width=\"1377\"\n"
        "     inkscape:window-height=\"779\"\n"
        "     id=\"namedview6\"\n"
        "     showgrid=\"false\"\n"
        "     inkscape:zoom=\"1.84375\"\n"
        "     inkscape:cx=\"90.456493\"\n"
        "     inkscape:cy=\"124.58161\"\n"
        "     inkscape:window-x=\"400\"\n"
        "     inkscape:window-y=\"93\"\n"
        "     inkscape:window-maximized=\"0\"\n"
        "     inkscape:current-layer=\"svg2\" />\n"
        "  <metadata\n"
        "     id=\"metadata7\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "        <dc:title></dc:title>\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <path\n"
        "     style=\"fill:#cbcaca;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:1.4105022px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n"
        "     d=\"M 38.614923,54.661521 37.733183,177.92104 222.81539,177.50163 222.25465,54.994123 Z m 9.68645,13.289785 163.023087,-1.154194 1.79738,102.540328 -164.379599,-1.38253 z M 20.758217,180.34262 c 3.642632,6.71821 -0.983508,19.5343 13.89205,19.86175 H 226.08709 c 10.42092,-0.18046 9.82323,-12.32745 11.58215,-19.86175 h -81.91298 c -1.22001,2.21984 0.2496,7.57747 -5.2841,8.87498 h -42.2791 c -5.51863,-0.27788 -5.39804,-5.18901 -6.36259,-8.87498 z\"\n"
        "     id=\"path838\"\n"
        "     inkscape:connector-curvature=\"0\"\n"
        "     sodipodi:nodetypes=\"ccccccccccccccccccc\" />\n"
        "  <path\n"
        "     style=\"opacity:1;fill:#cbcaca;fill-opacity:1;stroke:none;stroke-width:20.12762642;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;paint-order:normal\"\n"
        "     d=\"m 130.82818,85.518284 a 37.47375,34.783398 0 0 0 -37.471731,34.783046 37.47375,34.783398 0 0 0 37.471731,34.78304 37.47375,34.783398 0 0 0 37.47443,-34.78304 37.47375,34.783398 0 0 0 -37.47443,-34.783046 z m -4.56117,10.500153 h 9.74308 l -0.74759,22.555213 14.98977,13.96324 -5.62183,5.72971 -17.23797,-16.11125 z\"\n"
        "     id=\"path866\"\n"
        "     inkscape:connector-curvature=\"0\" />\n"
        "</svg>\n"
    ;
    return sRet.c_str();
} //::buffer() 

