// automaticly generated by update_resources.py


#include <resources_manager.h>

class RES_server_conf : public ResourceFile { 
    public:
        virtual const std::string &filename();
        virtual const int bufferSize();
        virtual const char *buffer();
};

