FROM debian:12
# stage build
LABEL "maintainer"="Evgenii Sopov <mrseakg@gmail.com>"
LABEL "repository"="https://github.com/sea-kg/ctf01d"

RUN apt-get -y update && apt-get -y upgrade && apt-get install -y \
    make cmake \
    g++ \
    pkg-config \
    libcurl4-openssl-dev \
    zlib1g zlib1g-dev \
    libpng-dev \
    python3 \
    python3-pip \
    && pip3 install --break-system-packages requests faker
