FROM debian:12
# stage release
LABEL "maintainer"="Evgenii Sopov <mrseakg@gmail.com>"
LABEL "repository"="https://github.com/sea-kg/ctf01d"

RUN apt-get -y update && apt-get -y upgrade && apt-get install -y \
    libcurl4 \
    zlib1g \
    libpng16-16 \
    libpthread-stubs0-dev \
    libssl-dev \
    nano \
    vim \
    python3 \
    python3-pip \
    && pip3 install requests faker

# COPY --from=0 /root/your-project/your-project.bin /usr/bin/your-project.bin

# EXPOSE 8080
# CMD ["your-project.bin","start"]